services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        container_name: backend
        env_file:
            - ./backend/.env
        volumes:
            - ./backend:/app
        command: air -c .air.toml
        ports:
            - "8080:8080"
        networks:
            - app-network

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        container_name: frontend
        env_file:
            - ./frontend/.env
        volumes:
            - ./frontend:/app
        command: npm run dev
        ports:
            - "3000:3000"
        depends_on:
            - backend
        networks:
            - app-network

    tgbot:
        build:
            context: ./tgbot
            dockerfile: Dockerfile.dev
        container_name: tgbot
        env_file:
            - ./tgbot/.env
        volumes:
            - ./tgbot:/app
        command: air -c .air.toml
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
