events {}
http {
    resolver 127.0.0.11 valid=30s;
    client_max_body_size 50M;
    server {
        listen 80;
        server_name api.kartonko.lol;
        set $backend_upstream "backend";
        location / {
            proxy_pass http://$backend_upstream:8080;
        }
    }
    server {
        listen 80;
        server_name kartonko.lol;
        set $frontend_upstream "frontend";
        location / {
            proxy_pass http://$frontend_upstream:3000;
        }
    }
}