// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tag

import (
	"context"
	"server/internal/tag"
	"server/internal/user"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockTagRepository creates a new instance of MockTagRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagRepository {
	mock := &MockTagRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTagRepository is an autogenerated mock type for the TagRepository type
type MockTagRepository struct {
	mock.Mock
}

type MockTagRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagRepository) EXPECT() *MockTagRepository_Expecter {
	return &MockTagRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTagRepository
func (_mock *MockTagRepository) Create(tag1 string) (*tag.Tag, error) {
	ret := _mock.Called(tag1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *tag.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*tag.Tag, error)); ok {
		return returnFunc(tag1)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *tag.Tag); ok {
		r0 = returnFunc(tag1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tag.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tag1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTagRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - tag1 string
func (_e *MockTagRepository_Expecter) Create(tag1 any) *MockTagRepository_Create_Call {
	return &MockTagRepository_Create_Call{Call: _e.mock.On("Create", tag1)}
}

func (_c *MockTagRepository_Create_Call) Run(run func(tag1 string)) *MockTagRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTagRepository_Create_Call) Return(tag11 *tag.Tag, err error) *MockTagRepository_Create_Call {
	_c.Call.Return(tag11, err)
	return _c
}

func (_c *MockTagRepository_Create_Call) RunAndReturn(run func(tag1 string) (*tag.Tag, error)) *MockTagRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ExistMany provides a mock function for the type MockTagRepository
func (_mock *MockTagRepository) ExistMany(tags []tag.Tag) ([]bool, error) {
	ret := _mock.Called(tags)

	if len(ret) == 0 {
		panic("no return value specified for ExistMany")
	}

	var r0 []bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]tag.Tag) ([]bool, error)); ok {
		return returnFunc(tags)
	}
	if returnFunc, ok := ret.Get(0).(func([]tag.Tag) []bool); ok {
		r0 = returnFunc(tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]tag.Tag) error); ok {
		r1 = returnFunc(tags)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagRepository_ExistMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistMany'
type MockTagRepository_ExistMany_Call struct {
	*mock.Call
}

// ExistMany is a helper method to define mock.On call
//   - tags []tag.Tag
func (_e *MockTagRepository_Expecter) ExistMany(tags any) *MockTagRepository_ExistMany_Call {
	return &MockTagRepository_ExistMany_Call{Call: _e.mock.On("ExistMany", tags)}
}

func (_c *MockTagRepository_ExistMany_Call) Run(run func(tags []tag.Tag)) *MockTagRepository_ExistMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []tag.Tag
		if args[0] != nil {
			arg0 = args[0].([]tag.Tag)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTagRepository_ExistMany_Call) Return(bools []bool, err error) *MockTagRepository_ExistMany_Call {
	_c.Call.Return(bools, err)
	return _c
}

func (_c *MockTagRepository_ExistMany_Call) RunAndReturn(run func(tags []tag.Tag) ([]bool, error)) *MockTagRepository_ExistMany_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockTagRepository
func (_mock *MockTagRepository) Exists(name string) (bool, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockTagRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - name string
func (_e *MockTagRepository_Expecter) Exists(name any) *MockTagRepository_Exists_Call {
	return &MockTagRepository_Exists_Call{Call: _e.mock.On("Exists", name)}
}

func (_c *MockTagRepository_Exists_Call) Run(run func(name string)) *MockTagRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTagRepository_Exists_Call) Return(b bool, err error) *MockTagRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTagRepository_Exists_Call) RunAndReturn(run func(name string) (bool, error)) *MockTagRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// SearchPrefix provides a mock function for the type MockTagRepository
func (_mock *MockTagRepository) SearchPrefix(prefix string, cursor int, limit int) ([]tag.Tag, error) {
	ret := _mock.Called(prefix, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchPrefix")
	}

	var r0 []tag.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int, int) ([]tag.Tag, error)); ok {
		return returnFunc(prefix, cursor, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, int) []tag.Tag); ok {
		r0 = returnFunc(prefix, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tag.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = returnFunc(prefix, cursor, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagRepository_SearchPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPrefix'
type MockTagRepository_SearchPrefix_Call struct {
	*mock.Call
}

// SearchPrefix is a helper method to define mock.On call
//   - prefix string
//   - cursor int
//   - limit int
func (_e *MockTagRepository_Expecter) SearchPrefix(prefix any, cursor any, limit any) *MockTagRepository_SearchPrefix_Call {
	return &MockTagRepository_SearchPrefix_Call{Call: _e.mock.On("SearchPrefix", prefix, cursor, limit)}
}

func (_c *MockTagRepository_SearchPrefix_Call) Run(run func(prefix string, cursor int, limit int)) *MockTagRepository_SearchPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTagRepository_SearchPrefix_Call) Return(tags []tag.Tag, err error) *MockTagRepository_SearchPrefix_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockTagRepository_SearchPrefix_Call) RunAndReturn(run func(prefix string, cursor int, limit int) ([]tag.Tag, error)) *MockTagRepository_SearchPrefix_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockTagRepository
func (_mock *MockTagRepository) WithTx(tx *gorm.DB) tag.TagRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 tag.TagRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) tag.TagRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tag.TagRepository)
		}
	}
	return r0
}

// MockTagRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockTagRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockTagRepository_Expecter) WithTx(tx any) *MockTagRepository_WithTx_Call {
	return &MockTagRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockTagRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockTagRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTagRepository_WithTx_Call) Return(tagRepository tag.TagRepository) *MockTagRepository_WithTx_Call {
	_c.Call.Return(tagRepository)
	return _c
}

func (_c *MockTagRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) tag.TagRepository) *MockTagRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTagService creates a new instance of MockTagService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagService {
	mock := &MockTagService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTagService is an autogenerated mock type for the TagService type
type MockTagService struct {
	mock.Mock
}

type MockTagService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagService) EXPECT() *MockTagService_Expecter {
	return &MockTagService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTagService
func (_mock *MockTagService) Create(ctx context.Context, tag1 string, user1 *user.User) (*tag.Tag, error) {
	ret := _mock.Called(ctx, tag1, user1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *tag.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *user.User) (*tag.Tag, error)); ok {
		return returnFunc(ctx, tag1, user1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *user.User) *tag.Tag); ok {
		r0 = returnFunc(ctx, tag1, user1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tag.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *user.User) error); ok {
		r1 = returnFunc(ctx, tag1, user1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTagService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tag1 string
//   - user1 *user.User
func (_e *MockTagService_Expecter) Create(ctx any, tag1 any, user1 any) *MockTagService_Create_Call {
	return &MockTagService_Create_Call{Call: _e.mock.On("Create", ctx, tag1, user1)}
}

func (_c *MockTagService_Create_Call) Run(run func(ctx context.Context, tag1 string, user1 *user.User)) *MockTagService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *user.User
		if args[2] != nil {
			arg2 = args[2].(*user.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTagService_Create_Call) Return(tag11 *tag.Tag, err error) *MockTagService_Create_Call {
	_c.Call.Return(tag11, err)
	return _c
}

func (_c *MockTagService_Create_Call) RunAndReturn(run func(ctx context.Context, tag1 string, user1 *user.User) (*tag.Tag, error)) *MockTagService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ExistMany provides a mock function for the type MockTagService
func (_mock *MockTagService) ExistMany(tags []tag.Tag) ([]bool, error) {
	ret := _mock.Called(tags)

	if len(ret) == 0 {
		panic("no return value specified for ExistMany")
	}

	var r0 []bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]tag.Tag) ([]bool, error)); ok {
		return returnFunc(tags)
	}
	if returnFunc, ok := ret.Get(0).(func([]tag.Tag) []bool); ok {
		r0 = returnFunc(tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]tag.Tag) error); ok {
		r1 = returnFunc(tags)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagService_ExistMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistMany'
type MockTagService_ExistMany_Call struct {
	*mock.Call
}

// ExistMany is a helper method to define mock.On call
//   - tags []tag.Tag
func (_e *MockTagService_Expecter) ExistMany(tags any) *MockTagService_ExistMany_Call {
	return &MockTagService_ExistMany_Call{Call: _e.mock.On("ExistMany", tags)}
}

func (_c *MockTagService_ExistMany_Call) Run(run func(tags []tag.Tag)) *MockTagService_ExistMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []tag.Tag
		if args[0] != nil {
			arg0 = args[0].([]tag.Tag)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTagService_ExistMany_Call) Return(bools []bool, err error) *MockTagService_ExistMany_Call {
	_c.Call.Return(bools, err)
	return _c
}

func (_c *MockTagService_ExistMany_Call) RunAndReturn(run func(tags []tag.Tag) ([]bool, error)) *MockTagService_ExistMany_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockTagService
func (_mock *MockTagService) Exists(name string) (bool, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagService_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockTagService_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - name string
func (_e *MockTagService_Expecter) Exists(name any) *MockTagService_Exists_Call {
	return &MockTagService_Exists_Call{Call: _e.mock.On("Exists", name)}
}

func (_c *MockTagService_Exists_Call) Run(run func(name string)) *MockTagService_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTagService_Exists_Call) Return(b bool, err error) *MockTagService_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTagService_Exists_Call) RunAndReturn(run func(name string) (bool, error)) *MockTagService_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// SearchPrefix provides a mock function for the type MockTagService
func (_mock *MockTagService) SearchPrefix(prefix string, cursor int, limit int) ([]tag.Tag, error) {
	ret := _mock.Called(prefix, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchPrefix")
	}

	var r0 []tag.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int, int) ([]tag.Tag, error)); ok {
		return returnFunc(prefix, cursor, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, int) []tag.Tag); ok {
		r0 = returnFunc(prefix, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tag.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = returnFunc(prefix, cursor, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagService_SearchPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPrefix'
type MockTagService_SearchPrefix_Call struct {
	*mock.Call
}

// SearchPrefix is a helper method to define mock.On call
//   - prefix string
//   - cursor int
//   - limit int
func (_e *MockTagService_Expecter) SearchPrefix(prefix any, cursor any, limit any) *MockTagService_SearchPrefix_Call {
	return &MockTagService_SearchPrefix_Call{Call: _e.mock.On("SearchPrefix", prefix, cursor, limit)}
}

func (_c *MockTagService_SearchPrefix_Call) Run(run func(prefix string, cursor int, limit int)) *MockTagService_SearchPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTagService_SearchPrefix_Call) Return(tags []tag.Tag, err error) *MockTagService_SearchPrefix_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockTagService_SearchPrefix_Call) RunAndReturn(run func(prefix string, cursor int, limit int) ([]tag.Tag, error)) *MockTagService_SearchPrefix_Call {
	_c.Call.Return(run)
	return _c
}
