// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package image

import (
	"context"
	"io"
	"mime/multipart"
	"server/internal/image"
	"server/internal/tag"
	"server/internal/user"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockObjectService creates a new instance of MockObjectService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectService {
	mock := &MockObjectService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObjectService is an autogenerated mock type for the ObjectService type
type MockObjectService struct {
	mock.Mock
}

type MockObjectService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectService) EXPECT() *MockObjectService_Expecter {
	return &MockObjectService_Expecter{mock: &_m.Mock}
}

// DeleteImageObjects provides a mock function for the type MockObjectService
func (_mock *MockObjectService) DeleteImageObjects(ctx context.Context, hash string, format string) error {
	ret := _mock.Called(ctx, hash, format)

	if len(ret) == 0 {
		panic("no return value specified for DeleteImageObjects")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, hash, format)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObjectService_DeleteImageObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteImageObjects'
type MockObjectService_DeleteImageObjects_Call struct {
	*mock.Call
}

// DeleteImageObjects is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
//   - format string
func (_e *MockObjectService_Expecter) DeleteImageObjects(ctx any, hash any, format any) *MockObjectService_DeleteImageObjects_Call {
	return &MockObjectService_DeleteImageObjects_Call{Call: _e.mock.On("DeleteImageObjects", ctx, hash, format)}
}

func (_c *MockObjectService_DeleteImageObjects_Call) Run(run func(ctx context.Context, hash string, format string)) *MockObjectService_DeleteImageObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockObjectService_DeleteImageObjects_Call) Return(err error) *MockObjectService_DeleteImageObjects_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObjectService_DeleteImageObjects_Call) RunAndReturn(run func(ctx context.Context, hash string, format string) error) *MockObjectService_DeleteImageObjects_Call {
	_c.Call.Return(run)
	return _c
}

// GetRawImage provides a mock function for the type MockObjectService
func (_mock *MockObjectService) GetRawImage(ctx context.Context, id uint) (io.ReadCloser, *image.ImageMetadata, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRawImage")
	}

	var r0 io.ReadCloser
	var r1 *image.ImageMetadata
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (io.ReadCloser, *image.ImageMetadata, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) io.ReadCloser); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) *image.ImageMetadata); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint) error); ok {
		r2 = returnFunc(ctx, id)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockObjectService_GetRawImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRawImage'
type MockObjectService_GetRawImage_Call struct {
	*mock.Call
}

// GetRawImage is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockObjectService_Expecter) GetRawImage(ctx any, id any) *MockObjectService_GetRawImage_Call {
	return &MockObjectService_GetRawImage_Call{Call: _e.mock.On("GetRawImage", ctx, id)}
}

func (_c *MockObjectService_GetRawImage_Call) Run(run func(ctx context.Context, id uint)) *MockObjectService_GetRawImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectService_GetRawImage_Call) Return(reader io.ReadCloser, img *image.ImageMetadata, err error) *MockObjectService_GetRawImage_Call {
	_c.Call.Return(reader, img, err)
	return _c
}

func (_c *MockObjectService_GetRawImage_Call) RunAndReturn(run func(ctx context.Context, id uint) (io.ReadCloser, *image.ImageMetadata, error)) *MockObjectService_GetRawImage_Call {
	_c.Call.Return(run)
	return _c
}

// GetRawImageByHash provides a mock function for the type MockObjectService
func (_mock *MockObjectService) GetRawImageByHash(ctx context.Context, hash string) (io.ReadCloser, *image.ImageMetadata, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetRawImageByHash")
	}

	var r0 io.ReadCloser
	var r1 *image.ImageMetadata
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, *image.ImageMetadata, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *image.ImageMetadata); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, hash)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockObjectService_GetRawImageByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRawImageByHash'
type MockObjectService_GetRawImageByHash_Call struct {
	*mock.Call
}

// GetRawImageByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockObjectService_Expecter) GetRawImageByHash(ctx any, hash any) *MockObjectService_GetRawImageByHash_Call {
	return &MockObjectService_GetRawImageByHash_Call{Call: _e.mock.On("GetRawImageByHash", ctx, hash)}
}

func (_c *MockObjectService_GetRawImageByHash_Call) Run(run func(ctx context.Context, hash string)) *MockObjectService_GetRawImageByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectService_GetRawImageByHash_Call) Return(reader io.ReadCloser, img *image.ImageMetadata, err error) *MockObjectService_GetRawImageByHash_Call {
	_c.Call.Return(reader, img, err)
	return _c
}

func (_c *MockObjectService_GetRawImageByHash_Call) RunAndReturn(run func(ctx context.Context, hash string) (io.ReadCloser, *image.ImageMetadata, error)) *MockObjectService_GetRawImageByHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetRawImageData provides a mock function for the type MockObjectService
func (_mock *MockObjectService) GetRawImageData(ctx context.Context, id uint) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRawImageData")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) io.ReadCloser); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectService_GetRawImageData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRawImageData'
type MockObjectService_GetRawImageData_Call struct {
	*mock.Call
}

// GetRawImageData is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockObjectService_Expecter) GetRawImageData(ctx any, id any) *MockObjectService_GetRawImageData_Call {
	return &MockObjectService_GetRawImageData_Call{Call: _e.mock.On("GetRawImageData", ctx, id)}
}

func (_c *MockObjectService_GetRawImageData_Call) Run(run func(ctx context.Context, id uint)) *MockObjectService_GetRawImageData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectService_GetRawImageData_Call) Return(readCloser io.ReadCloser, err error) *MockObjectService_GetRawImageData_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockObjectService_GetRawImageData_Call) RunAndReturn(run func(ctx context.Context, id uint) (io.ReadCloser, error)) *MockObjectService_GetRawImageData_Call {
	_c.Call.Return(run)
	return _c
}

// GetRawThumbnail provides a mock function for the type MockObjectService
func (_mock *MockObjectService) GetRawThumbnail(ctx context.Context, id uint) (io.ReadCloser, *image.ImageMetadata, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRawThumbnail")
	}

	var r0 io.ReadCloser
	var r1 *image.ImageMetadata
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (io.ReadCloser, *image.ImageMetadata, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) io.ReadCloser); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) *image.ImageMetadata); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint) error); ok {
		r2 = returnFunc(ctx, id)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockObjectService_GetRawThumbnail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRawThumbnail'
type MockObjectService_GetRawThumbnail_Call struct {
	*mock.Call
}

// GetRawThumbnail is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockObjectService_Expecter) GetRawThumbnail(ctx any, id any) *MockObjectService_GetRawThumbnail_Call {
	return &MockObjectService_GetRawThumbnail_Call{Call: _e.mock.On("GetRawThumbnail", ctx, id)}
}

func (_c *MockObjectService_GetRawThumbnail_Call) Run(run func(ctx context.Context, id uint)) *MockObjectService_GetRawThumbnail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectService_GetRawThumbnail_Call) Return(reader io.ReadCloser, img *image.ImageMetadata, err error) *MockObjectService_GetRawThumbnail_Call {
	_c.Call.Return(reader, img, err)
	return _c
}

func (_c *MockObjectService_GetRawThumbnail_Call) RunAndReturn(run func(ctx context.Context, id uint) (io.ReadCloser, *image.ImageMetadata, error)) *MockObjectService_GetRawThumbnail_Call {
	_c.Call.Return(run)
	return _c
}

// GetRawThumbnailByHash provides a mock function for the type MockObjectService
func (_mock *MockObjectService) GetRawThumbnailByHash(ctx context.Context, hash string) (io.ReadCloser, *image.ImageMetadata, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetRawThumbnailByHash")
	}

	var r0 io.ReadCloser
	var r1 *image.ImageMetadata
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, *image.ImageMetadata, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *image.ImageMetadata); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, hash)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockObjectService_GetRawThumbnailByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRawThumbnailByHash'
type MockObjectService_GetRawThumbnailByHash_Call struct {
	*mock.Call
}

// GetRawThumbnailByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockObjectService_Expecter) GetRawThumbnailByHash(ctx any, hash any) *MockObjectService_GetRawThumbnailByHash_Call {
	return &MockObjectService_GetRawThumbnailByHash_Call{Call: _e.mock.On("GetRawThumbnailByHash", ctx, hash)}
}

func (_c *MockObjectService_GetRawThumbnailByHash_Call) Run(run func(ctx context.Context, hash string)) *MockObjectService_GetRawThumbnailByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectService_GetRawThumbnailByHash_Call) Return(reader io.ReadCloser, img *image.ImageMetadata, err error) *MockObjectService_GetRawThumbnailByHash_Call {
	_c.Call.Return(reader, img, err)
	return _c
}

func (_c *MockObjectService_GetRawThumbnailByHash_Call) RunAndReturn(run func(ctx context.Context, hash string) (io.ReadCloser, *image.ImageMetadata, error)) *MockObjectService_GetRawThumbnailByHash_Call {
	_c.Call.Return(run)
	return _c
}

// UploadImage provides a mock function for the type MockObjectService
func (_mock *MockObjectService) UploadImage(ctx context.Context, hash string, format image.Format, data []byte) error {
	ret := _mock.Called(ctx, hash, format, data)

	if len(ret) == 0 {
		panic("no return value specified for UploadImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, image.Format, []byte) error); ok {
		r0 = returnFunc(ctx, hash, format, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObjectService_UploadImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadImage'
type MockObjectService_UploadImage_Call struct {
	*mock.Call
}

// UploadImage is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
//   - format image.Format
//   - data []byte
func (_e *MockObjectService_Expecter) UploadImage(ctx any, hash any, format any, data any) *MockObjectService_UploadImage_Call {
	return &MockObjectService_UploadImage_Call{Call: _e.mock.On("UploadImage", ctx, hash, format, data)}
}

func (_c *MockObjectService_UploadImage_Call) Run(run func(ctx context.Context, hash string, format image.Format, data []byte)) *MockObjectService_UploadImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 image.Format
		if args[2] != nil {
			arg2 = args[2].(image.Format)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockObjectService_UploadImage_Call) Return(err error) *MockObjectService_UploadImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObjectService_UploadImage_Call) RunAndReturn(run func(ctx context.Context, hash string, format image.Format, data []byte) error) *MockObjectService_UploadImage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImageRepository creates a new instance of MockImageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageRepository {
	mock := &MockImageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageRepository is an autogenerated mock type for the ImageRepository type
type MockImageRepository struct {
	mock.Mock
}

type MockImageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageRepository) EXPECT() *MockImageRepository_Expecter {
	return &MockImageRepository_Expecter{mock: &_m.Mock}
}

// AttachTags provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) AttachTags(imageID uint, tags []tag.Tag) error {
	ret := _mock.Called(imageID, tags)

	if len(ret) == 0 {
		panic("no return value specified for AttachTags")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, []tag.Tag) error); ok {
		r0 = returnFunc(imageID, tags)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageRepository_AttachTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachTags'
type MockImageRepository_AttachTags_Call struct {
	*mock.Call
}

// AttachTags is a helper method to define mock.On call
//   - imageID uint
//   - tags []tag.Tag
func (_e *MockImageRepository_Expecter) AttachTags(imageID any, tags any) *MockImageRepository_AttachTags_Call {
	return &MockImageRepository_AttachTags_Call{Call: _e.mock.On("AttachTags", imageID, tags)}
}

func (_c *MockImageRepository_AttachTags_Call) Run(run func(imageID uint, tags []tag.Tag)) *MockImageRepository_AttachTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 []tag.Tag
		if args[1] != nil {
			arg1 = args[1].([]tag.Tag)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_AttachTags_Call) Return(err error) *MockImageRepository_AttachTags_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageRepository_AttachTags_Call) RunAndReturn(run func(imageID uint, tags []tag.Tag) error) *MockImageRepository_AttachTags_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) Count(query *image.Query) (int64, error) {
	ret := _mock.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*image.Query) (int64, error)); ok {
		return returnFunc(query)
	}
	if returnFunc, ok := ret.Get(0).(func(*image.Query) int64); ok {
		r0 = returnFunc(query)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*image.Query) error); ok {
		r1 = returnFunc(query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockImageRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - query *image.Query
func (_e *MockImageRepository_Expecter) Count(query any) *MockImageRepository_Count_Call {
	return &MockImageRepository_Count_Call{Call: _e.mock.On("Count", query)}
}

func (_c *MockImageRepository_Count_Call) Run(run func(query *image.Query)) *MockImageRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *image.Query
		if args[0] != nil {
			arg0 = args[0].(*image.Query)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageRepository_Count_Call) Return(n int64, err error) *MockImageRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockImageRepository_Count_Call) RunAndReturn(run func(query *image.Query) (int64, error)) *MockImageRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) Create(image1 *image.ImageMetadata) error {
	ret := _mock.Called(image1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*image.ImageMetadata) error); ok {
		r0 = returnFunc(image1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockImageRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - image1 *image.ImageMetadata
func (_e *MockImageRepository_Expecter) Create(image1 any) *MockImageRepository_Create_Call {
	return &MockImageRepository_Create_Call{Call: _e.mock.On("Create", image1)}
}

func (_c *MockImageRepository_Create_Call) Run(run func(image1 *image.ImageMetadata)) *MockImageRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *image.ImageMetadata
		if args[0] != nil {
			arg0 = args[0].(*image.ImageMetadata)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageRepository_Create_Call) Return(err error) *MockImageRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageRepository_Create_Call) RunAndReturn(run func(image1 *image.ImageMetadata) error) *MockImageRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) DeleteByID(id uint) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockImageRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - id uint
func (_e *MockImageRepository_Expecter) DeleteByID(id any) *MockImageRepository_DeleteByID_Call {
	return &MockImageRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", id)}
}

func (_c *MockImageRepository_DeleteByID_Call) Run(run func(id uint)) *MockImageRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageRepository_DeleteByID_Call) Return(err error) *MockImageRepository_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageRepository_DeleteByID_Call) RunAndReturn(run func(id uint) error) *MockImageRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByIDs provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) DeleteByIDs(ids []uint) error {
	ret := _mock.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByIDs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]uint) error); ok {
		r0 = returnFunc(ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageRepository_DeleteByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByIDs'
type MockImageRepository_DeleteByIDs_Call struct {
	*mock.Call
}

// DeleteByIDs is a helper method to define mock.On call
//   - ids []uint
func (_e *MockImageRepository_Expecter) DeleteByIDs(ids any) *MockImageRepository_DeleteByIDs_Call {
	return &MockImageRepository_DeleteByIDs_Call{Call: _e.mock.On("DeleteByIDs", ids)}
}

func (_c *MockImageRepository_DeleteByIDs_Call) Run(run func(ids []uint)) *MockImageRepository_DeleteByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []uint
		if args[0] != nil {
			arg0 = args[0].([]uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageRepository_DeleteByIDs_Call) Return(err error) *MockImageRepository_DeleteByIDs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageRepository_DeleteByIDs_Call) RunAndReturn(run func(ids []uint) error) *MockImageRepository_DeleteByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByHash provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) ExistsByHash(hash string) (bool, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByHash")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_ExistsByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByHash'
type MockImageRepository_ExistsByHash_Call struct {
	*mock.Call
}

// ExistsByHash is a helper method to define mock.On call
//   - hash string
func (_e *MockImageRepository_Expecter) ExistsByHash(hash any) *MockImageRepository_ExistsByHash_Call {
	return &MockImageRepository_ExistsByHash_Call{Call: _e.mock.On("ExistsByHash", hash)}
}

func (_c *MockImageRepository_ExistsByHash_Call) Run(run func(hash string)) *MockImageRepository_ExistsByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageRepository_ExistsByHash_Call) Return(b bool, err error) *MockImageRepository_ExistsByHash_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockImageRepository_ExistsByHash_Call) RunAndReturn(run func(hash string) (bool, error)) *MockImageRepository_ExistsByHash_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByName provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) ExistsByName(name string) (bool, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByName")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_ExistsByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByName'
type MockImageRepository_ExistsByName_Call struct {
	*mock.Call
}

// ExistsByName is a helper method to define mock.On call
//   - name string
func (_e *MockImageRepository_Expecter) ExistsByName(name any) *MockImageRepository_ExistsByName_Call {
	return &MockImageRepository_ExistsByName_Call{Call: _e.mock.On("ExistsByName", name)}
}

func (_c *MockImageRepository_ExistsByName_Call) Run(run func(name string)) *MockImageRepository_ExistsByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageRepository_ExistsByName_Call) Return(b bool, err error) *MockImageRepository_ExistsByName_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockImageRepository_ExistsByName_Call) RunAndReturn(run func(name string) (bool, error)) *MockImageRepository_ExistsByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetByHash provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) GetByHash(hash string) (*image.ImageMetadata, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for GetByHash")
	}

	var r0 *image.ImageMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*image.ImageMetadata, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *image.ImageMetadata); ok {
		r0 = returnFunc(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_GetByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHash'
type MockImageRepository_GetByHash_Call struct {
	*mock.Call
}

// GetByHash is a helper method to define mock.On call
//   - hash string
func (_e *MockImageRepository_Expecter) GetByHash(hash any) *MockImageRepository_GetByHash_Call {
	return &MockImageRepository_GetByHash_Call{Call: _e.mock.On("GetByHash", hash)}
}

func (_c *MockImageRepository_GetByHash_Call) Run(run func(hash string)) *MockImageRepository_GetByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageRepository_GetByHash_Call) Return(imageMetadata *image.ImageMetadata, err error) *MockImageRepository_GetByHash_Call {
	_c.Call.Return(imageMetadata, err)
	return _c
}

func (_c *MockImageRepository_GetByHash_Call) RunAndReturn(run func(hash string) (*image.ImageMetadata, error)) *MockImageRepository_GetByHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) GetByID(id uint) (*image.ImageMetadata, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *image.ImageMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*image.ImageMetadata, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *image.ImageMetadata); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockImageRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *MockImageRepository_Expecter) GetByID(id any) *MockImageRepository_GetByID_Call {
	return &MockImageRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockImageRepository_GetByID_Call) Run(run func(id uint)) *MockImageRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageRepository_GetByID_Call) Return(imageMetadata *image.ImageMetadata, err error) *MockImageRepository_GetByID_Call {
	_c.Call.Return(imageMetadata, err)
	return _c
}

func (_c *MockImageRepository_GetByID_Call) RunAndReturn(run func(id uint) (*image.ImageMetadata, error)) *MockImageRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) GetByName(name string) (*image.ImageMetadata, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *image.ImageMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*image.ImageMetadata, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *image.ImageMetadata); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockImageRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - name string
func (_e *MockImageRepository_Expecter) GetByName(name any) *MockImageRepository_GetByName_Call {
	return &MockImageRepository_GetByName_Call{Call: _e.mock.On("GetByName", name)}
}

func (_c *MockImageRepository_GetByName_Call) Run(run func(name string)) *MockImageRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageRepository_GetByName_Call) Return(imageMetadata *image.ImageMetadata, err error) *MockImageRepository_GetByName_Call {
	_c.Call.Return(imageMetadata, err)
	return _c
}

func (_c *MockImageRepository_GetByName_Call) RunAndReturn(run func(name string) (*image.ImageMetadata, error)) *MockImageRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) Search(query *image.Query) ([]image.ImageMetadata, error) {
	ret := _mock.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []image.ImageMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*image.Query) ([]image.ImageMetadata, error)); ok {
		return returnFunc(query)
	}
	if returnFunc, ok := ret.Get(0).(func(*image.Query) []image.ImageMetadata); ok {
		r0 = returnFunc(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*image.Query) error); ok {
		r1 = returnFunc(query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockImageRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - query *image.Query
func (_e *MockImageRepository_Expecter) Search(query any) *MockImageRepository_Search_Call {
	return &MockImageRepository_Search_Call{Call: _e.mock.On("Search", query)}
}

func (_c *MockImageRepository_Search_Call) Run(run func(query *image.Query)) *MockImageRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *image.Query
		if args[0] != nil {
			arg0 = args[0].(*image.Query)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageRepository_Search_Call) Return(imageMetadatas []image.ImageMetadata, err error) *MockImageRepository_Search_Call {
	_c.Call.Return(imageMetadatas, err)
	return _c
}

func (_c *MockImageRepository_Search_Call) RunAndReturn(run func(query *image.Query) ([]image.ImageMetadata, error)) *MockImageRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) Update(image1 *image.ImageMetadata) error {
	ret := _mock.Called(image1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*image.ImageMetadata) error); ok {
		r0 = returnFunc(image1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockImageRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - image1 *image.ImageMetadata
func (_e *MockImageRepository_Expecter) Update(image1 any) *MockImageRepository_Update_Call {
	return &MockImageRepository_Update_Call{Call: _e.mock.On("Update", image1)}
}

func (_c *MockImageRepository_Update_Call) Run(run func(image1 *image.ImageMetadata)) *MockImageRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *image.ImageMetadata
		if args[0] != nil {
			arg0 = args[0].(*image.ImageMetadata)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageRepository_Update_Call) Return(err error) *MockImageRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageRepository_Update_Call) RunAndReturn(run func(image1 *image.ImageMetadata) error) *MockImageRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) WithTx(tx *gorm.DB) image.ImageRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 image.ImageRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) image.ImageRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(image.ImageRepository)
		}
	}
	return r0
}

// MockImageRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockImageRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockImageRepository_Expecter) WithTx(tx any) *MockImageRepository_WithTx_Call {
	return &MockImageRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockImageRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockImageRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageRepository_WithTx_Call) Return(imageRepository image.ImageRepository) *MockImageRepository_WithTx_Call {
	_c.Call.Return(imageRepository)
	return _c
}

func (_c *MockImageRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) image.ImageRepository) *MockImageRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImageService creates a new instance of MockImageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageService {
	mock := &MockImageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageService is an autogenerated mock type for the ImageService type
type MockImageService struct {
	mock.Mock
}

type MockImageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageService) EXPECT() *MockImageService_Expecter {
	return &MockImageService_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockImageService
func (_mock *MockImageService) Count(query *image.Query) (int64, error) {
	ret := _mock.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*image.Query) (int64, error)); ok {
		return returnFunc(query)
	}
	if returnFunc, ok := ret.Get(0).(func(*image.Query) int64); ok {
		r0 = returnFunc(query)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*image.Query) error); ok {
		r1 = returnFunc(query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageService_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockImageService_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - query *image.Query
func (_e *MockImageService_Expecter) Count(query any) *MockImageService_Count_Call {
	return &MockImageService_Count_Call{Call: _e.mock.On("Count", query)}
}

func (_c *MockImageService_Count_Call) Run(run func(query *image.Query)) *MockImageService_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *image.Query
		if args[0] != nil {
			arg0 = args[0].(*image.Query)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageService_Count_Call) Return(n int64, err error) *MockImageService_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockImageService_Count_Call) RunAndReturn(run func(query *image.Query) (int64, error)) *MockImageService_Count_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockImageService
func (_mock *MockImageService) DeleteByID(ctx context.Context, user1 *user.User, id uint) error {
	ret := _mock.Called(ctx, user1, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.User, uint) error); ok {
		r0 = returnFunc(ctx, user1, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageService_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockImageService_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - user1 *user.User
//   - id uint
func (_e *MockImageService_Expecter) DeleteByID(ctx any, user1 any, id any) *MockImageService_DeleteByID_Call {
	return &MockImageService_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, user1, id)}
}

func (_c *MockImageService_DeleteByID_Call) Run(run func(ctx context.Context, user1 *user.User, id uint)) *MockImageService_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.User
		if args[1] != nil {
			arg1 = args[1].(*user.User)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageService_DeleteByID_Call) Return(err error) *MockImageService_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageService_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, user1 *user.User, id uint) error) *MockImageService_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByName provides a mock function for the type MockImageService
func (_mock *MockImageService) DeleteByName(ctx context.Context, user1 *user.User, name string) error {
	ret := _mock.Called(ctx, user1, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.User, string) error); ok {
		r0 = returnFunc(ctx, user1, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageService_DeleteByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByName'
type MockImageService_DeleteByName_Call struct {
	*mock.Call
}

// DeleteByName is a helper method to define mock.On call
//   - ctx context.Context
//   - user1 *user.User
//   - name string
func (_e *MockImageService_Expecter) DeleteByName(ctx any, user1 any, name any) *MockImageService_DeleteByName_Call {
	return &MockImageService_DeleteByName_Call{Call: _e.mock.On("DeleteByName", ctx, user1, name)}
}

func (_c *MockImageService_DeleteByName_Call) Run(run func(ctx context.Context, user1 *user.User, name string)) *MockImageService_DeleteByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.User
		if args[1] != nil {
			arg1 = args[1].(*user.User)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageService_DeleteByName_Call) Return(err error) *MockImageService_DeleteByName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageService_DeleteByName_Call) RunAndReturn(run func(ctx context.Context, user1 *user.User, name string) error) *MockImageService_DeleteByName_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByQuery provides a mock function for the type MockImageService
func (_mock *MockImageService) DeleteByQuery(ctx context.Context, user1 *user.User, query *image.Query) []error {
	ret := _mock.Called(ctx, user1, query)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByQuery")
	}

	var r0 []error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.User, *image.Query) []error); ok {
		r0 = returnFunc(ctx, user1, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}
	return r0
}

// MockImageService_DeleteByQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByQuery'
type MockImageService_DeleteByQuery_Call struct {
	*mock.Call
}

// DeleteByQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - user1 *user.User
//   - query *image.Query
func (_e *MockImageService_Expecter) DeleteByQuery(ctx any, user1 any, query any) *MockImageService_DeleteByQuery_Call {
	return &MockImageService_DeleteByQuery_Call{Call: _e.mock.On("DeleteByQuery", ctx, user1, query)}
}

func (_c *MockImageService_DeleteByQuery_Call) Run(run func(ctx context.Context, user1 *user.User, query *image.Query)) *MockImageService_DeleteByQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.User
		if args[1] != nil {
			arg1 = args[1].(*user.User)
		}
		var arg2 *image.Query
		if args[2] != nil {
			arg2 = args[2].(*image.Query)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageService_DeleteByQuery_Call) Return(errs []error) *MockImageService_DeleteByQuery_Call {
	_c.Call.Return(errs)
	return _c
}

func (_c *MockImageService_DeleteByQuery_Call) RunAndReturn(run func(ctx context.Context, user1 *user.User, query *image.Query) []error) *MockImageService_DeleteByQuery_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByHash provides a mock function for the type MockImageService
func (_mock *MockImageService) ExistsByHash(hash string) (bool, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByHash")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageService_ExistsByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByHash'
type MockImageService_ExistsByHash_Call struct {
	*mock.Call
}

// ExistsByHash is a helper method to define mock.On call
//   - hash string
func (_e *MockImageService_Expecter) ExistsByHash(hash any) *MockImageService_ExistsByHash_Call {
	return &MockImageService_ExistsByHash_Call{Call: _e.mock.On("ExistsByHash", hash)}
}

func (_c *MockImageService_ExistsByHash_Call) Run(run func(hash string)) *MockImageService_ExistsByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageService_ExistsByHash_Call) Return(b bool, err error) *MockImageService_ExistsByHash_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockImageService_ExistsByHash_Call) RunAndReturn(run func(hash string) (bool, error)) *MockImageService_ExistsByHash_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByName provides a mock function for the type MockImageService
func (_mock *MockImageService) ExistsByName(name string) (bool, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByName")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageService_ExistsByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByName'
type MockImageService_ExistsByName_Call struct {
	*mock.Call
}

// ExistsByName is a helper method to define mock.On call
//   - name string
func (_e *MockImageService_Expecter) ExistsByName(name any) *MockImageService_ExistsByName_Call {
	return &MockImageService_ExistsByName_Call{Call: _e.mock.On("ExistsByName", name)}
}

func (_c *MockImageService_ExistsByName_Call) Run(run func(name string)) *MockImageService_ExistsByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageService_ExistsByName_Call) Return(b bool, err error) *MockImageService_ExistsByName_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockImageService_ExistsByName_Call) RunAndReturn(run func(name string) (bool, error)) *MockImageService_ExistsByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetByHash provides a mock function for the type MockImageService
func (_mock *MockImageService) GetByHash(hash string) (*image.ImageMetadata, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for GetByHash")
	}

	var r0 *image.ImageMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*image.ImageMetadata, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *image.ImageMetadata); ok {
		r0 = returnFunc(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageService_GetByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHash'
type MockImageService_GetByHash_Call struct {
	*mock.Call
}

// GetByHash is a helper method to define mock.On call
//   - hash string
func (_e *MockImageService_Expecter) GetByHash(hash any) *MockImageService_GetByHash_Call {
	return &MockImageService_GetByHash_Call{Call: _e.mock.On("GetByHash", hash)}
}

func (_c *MockImageService_GetByHash_Call) Run(run func(hash string)) *MockImageService_GetByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageService_GetByHash_Call) Return(imageMetadata *image.ImageMetadata, err error) *MockImageService_GetByHash_Call {
	_c.Call.Return(imageMetadata, err)
	return _c
}

func (_c *MockImageService_GetByHash_Call) RunAndReturn(run func(hash string) (*image.ImageMetadata, error)) *MockImageService_GetByHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockImageService
func (_mock *MockImageService) GetByID(id uint) (*image.ImageMetadata, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *image.ImageMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*image.ImageMetadata, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *image.ImageMetadata); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockImageService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *MockImageService_Expecter) GetByID(id any) *MockImageService_GetByID_Call {
	return &MockImageService_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockImageService_GetByID_Call) Run(run func(id uint)) *MockImageService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageService_GetByID_Call) Return(imageMetadata *image.ImageMetadata, err error) *MockImageService_GetByID_Call {
	_c.Call.Return(imageMetadata, err)
	return _c
}

func (_c *MockImageService_GetByID_Call) RunAndReturn(run func(id uint) (*image.ImageMetadata, error)) *MockImageService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type MockImageService
func (_mock *MockImageService) GetByName(name string) (*image.ImageMetadata, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *image.ImageMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*image.ImageMetadata, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *image.ImageMetadata); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageService_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockImageService_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - name string
func (_e *MockImageService_Expecter) GetByName(name any) *MockImageService_GetByName_Call {
	return &MockImageService_GetByName_Call{Call: _e.mock.On("GetByName", name)}
}

func (_c *MockImageService_GetByName_Call) Run(run func(name string)) *MockImageService_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageService_GetByName_Call) Return(imageMetadata *image.ImageMetadata, err error) *MockImageService_GetByName_Call {
	_c.Call.Return(imageMetadata, err)
	return _c
}

func (_c *MockImageService_GetByName_Call) RunAndReturn(run func(name string) (*image.ImageMetadata, error)) *MockImageService_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockImageService
func (_mock *MockImageService) Search(query *image.Query) ([]image.ImageMetadata, error) {
	ret := _mock.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []image.ImageMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*image.Query) ([]image.ImageMetadata, error)); ok {
		return returnFunc(query)
	}
	if returnFunc, ok := ret.Get(0).(func(*image.Query) []image.ImageMetadata); ok {
		r0 = returnFunc(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*image.Query) error); ok {
		r1 = returnFunc(query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockImageService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - query *image.Query
func (_e *MockImageService_Expecter) Search(query any) *MockImageService_Search_Call {
	return &MockImageService_Search_Call{Call: _e.mock.On("Search", query)}
}

func (_c *MockImageService_Search_Call) Run(run func(query *image.Query)) *MockImageService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *image.Query
		if args[0] != nil {
			arg0 = args[0].(*image.Query)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageService_Search_Call) Return(imageMetadatas []image.ImageMetadata, err error) *MockImageService_Search_Call {
	_c.Call.Return(imageMetadatas, err)
	return _c
}

func (_c *MockImageService_Search_Call) RunAndReturn(run func(query *image.Query) ([]image.ImageMetadata, error)) *MockImageService_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockImageService
func (_mock *MockImageService) Upload(ctx context.Context, userID uint, uploadMetadata *image.ImagePostRequest, fileHeader *multipart.FileHeader) (*image.ImageMetadata, error) {
	ret := _mock.Called(ctx, userID, uploadMetadata, fileHeader)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 *image.ImageMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, *image.ImagePostRequest, *multipart.FileHeader) (*image.ImageMetadata, error)); ok {
		return returnFunc(ctx, userID, uploadMetadata, fileHeader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, *image.ImagePostRequest, *multipart.FileHeader) *image.ImageMetadata); ok {
		r0 = returnFunc(ctx, userID, uploadMetadata, fileHeader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, *image.ImagePostRequest, *multipart.FileHeader) error); ok {
		r1 = returnFunc(ctx, userID, uploadMetadata, fileHeader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageService_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockImageService_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - uploadMetadata *image.ImagePostRequest
//   - fileHeader *multipart.FileHeader
func (_e *MockImageService_Expecter) Upload(ctx any, userID any, uploadMetadata any, fileHeader any) *MockImageService_Upload_Call {
	return &MockImageService_Upload_Call{Call: _e.mock.On("Upload", ctx, userID, uploadMetadata, fileHeader)}
}

func (_c *MockImageService_Upload_Call) Run(run func(ctx context.Context, userID uint, uploadMetadata *image.ImagePostRequest, fileHeader *multipart.FileHeader)) *MockImageService_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 *image.ImagePostRequest
		if args[2] != nil {
			arg2 = args[2].(*image.ImagePostRequest)
		}
		var arg3 *multipart.FileHeader
		if args[3] != nil {
			arg3 = args[3].(*multipart.FileHeader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockImageService_Upload_Call) Return(imageMetadata *image.ImageMetadata, err error) *MockImageService_Upload_Call {
	_c.Call.Return(imageMetadata, err)
	return _c
}

func (_c *MockImageService_Upload_Call) RunAndReturn(run func(ctx context.Context, userID uint, uploadMetadata *image.ImagePostRequest, fileHeader *multipart.FileHeader) (*image.ImageMetadata, error)) *MockImageService_Upload_Call {
	_c.Call.Return(run)
	return _c
}
