// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package image

import (
	"context"
	"io"
	"server/internal/image"
	"server/internal/tag"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockObjectService creates a new instance of MockObjectService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectService {
	mock := &MockObjectService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObjectService is an autogenerated mock type for the ObjectService type
type MockObjectService struct {
	mock.Mock
}

type MockObjectService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectService) EXPECT() *MockObjectService_Expecter {
	return &MockObjectService_Expecter{mock: &_m.Mock}
}

// DeleteImageObjects provides a mock function for the type MockObjectService
func (_mock *MockObjectService) DeleteImageObjects(ctx context.Context, hash string, format string) error {
	ret := _mock.Called(ctx, hash, format)

	if len(ret) == 0 {
		panic("no return value specified for DeleteImageObjects")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, hash, format)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObjectService_DeleteImageObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteImageObjects'
type MockObjectService_DeleteImageObjects_Call struct {
	*mock.Call
}

// DeleteImageObjects is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
//   - format string
func (_e *MockObjectService_Expecter) DeleteImageObjects(ctx any, hash any, format any) *MockObjectService_DeleteImageObjects_Call {
	return &MockObjectService_DeleteImageObjects_Call{Call: _e.mock.On("DeleteImageObjects", ctx, hash, format)}
}

func (_c *MockObjectService_DeleteImageObjects_Call) Run(run func(ctx context.Context, hash string, format string)) *MockObjectService_DeleteImageObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockObjectService_DeleteImageObjects_Call) Return(err error) *MockObjectService_DeleteImageObjects_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObjectService_DeleteImageObjects_Call) RunAndReturn(run func(ctx context.Context, hash string, format string) error) *MockObjectService_DeleteImageObjects_Call {
	_c.Call.Return(run)
	return _c
}

// GetRawImage provides a mock function for the type MockObjectService
func (_mock *MockObjectService) GetRawImage(ctx context.Context, id uint) (io.ReadCloser, *image.ImageMetadata, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRawImage")
	}

	var r0 io.ReadCloser
	var r1 *image.ImageMetadata
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (io.ReadCloser, *image.ImageMetadata, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) io.ReadCloser); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) *image.ImageMetadata); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint) error); ok {
		r2 = returnFunc(ctx, id)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockObjectService_GetRawImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRawImage'
type MockObjectService_GetRawImage_Call struct {
	*mock.Call
}

// GetRawImage is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockObjectService_Expecter) GetRawImage(ctx any, id any) *MockObjectService_GetRawImage_Call {
	return &MockObjectService_GetRawImage_Call{Call: _e.mock.On("GetRawImage", ctx, id)}
}

func (_c *MockObjectService_GetRawImage_Call) Run(run func(ctx context.Context, id uint)) *MockObjectService_GetRawImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectService_GetRawImage_Call) Return(reader io.ReadCloser, img *image.ImageMetadata, err error) *MockObjectService_GetRawImage_Call {
	_c.Call.Return(reader, img, err)
	return _c
}

func (_c *MockObjectService_GetRawImage_Call) RunAndReturn(run func(ctx context.Context, id uint) (io.ReadCloser, *image.ImageMetadata, error)) *MockObjectService_GetRawImage_Call {
	_c.Call.Return(run)
	return _c
}

// GetRawImageByHash provides a mock function for the type MockObjectService
func (_mock *MockObjectService) GetRawImageByHash(ctx context.Context, hash string) (io.ReadCloser, *image.ImageMetadata, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetRawImageByHash")
	}

	var r0 io.ReadCloser
	var r1 *image.ImageMetadata
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, *image.ImageMetadata, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *image.ImageMetadata); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, hash)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockObjectService_GetRawImageByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRawImageByHash'
type MockObjectService_GetRawImageByHash_Call struct {
	*mock.Call
}

// GetRawImageByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockObjectService_Expecter) GetRawImageByHash(ctx any, hash any) *MockObjectService_GetRawImageByHash_Call {
	return &MockObjectService_GetRawImageByHash_Call{Call: _e.mock.On("GetRawImageByHash", ctx, hash)}
}

func (_c *MockObjectService_GetRawImageByHash_Call) Run(run func(ctx context.Context, hash string)) *MockObjectService_GetRawImageByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectService_GetRawImageByHash_Call) Return(reader io.ReadCloser, img *image.ImageMetadata, err error) *MockObjectService_GetRawImageByHash_Call {
	_c.Call.Return(reader, img, err)
	return _c
}

func (_c *MockObjectService_GetRawImageByHash_Call) RunAndReturn(run func(ctx context.Context, hash string) (io.ReadCloser, *image.ImageMetadata, error)) *MockObjectService_GetRawImageByHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetRawImageData provides a mock function for the type MockObjectService
func (_mock *MockObjectService) GetRawImageData(ctx context.Context, id uint) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRawImageData")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) io.ReadCloser); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectService_GetRawImageData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRawImageData'
type MockObjectService_GetRawImageData_Call struct {
	*mock.Call
}

// GetRawImageData is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockObjectService_Expecter) GetRawImageData(ctx any, id any) *MockObjectService_GetRawImageData_Call {
	return &MockObjectService_GetRawImageData_Call{Call: _e.mock.On("GetRawImageData", ctx, id)}
}

func (_c *MockObjectService_GetRawImageData_Call) Run(run func(ctx context.Context, id uint)) *MockObjectService_GetRawImageData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectService_GetRawImageData_Call) Return(readCloser io.ReadCloser, err error) *MockObjectService_GetRawImageData_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockObjectService_GetRawImageData_Call) RunAndReturn(run func(ctx context.Context, id uint) (io.ReadCloser, error)) *MockObjectService_GetRawImageData_Call {
	_c.Call.Return(run)
	return _c
}

// GetRawThumbnail provides a mock function for the type MockObjectService
func (_mock *MockObjectService) GetRawThumbnail(ctx context.Context, id uint) (io.ReadCloser, *image.ImageMetadata, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRawThumbnail")
	}

	var r0 io.ReadCloser
	var r1 *image.ImageMetadata
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (io.ReadCloser, *image.ImageMetadata, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) io.ReadCloser); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) *image.ImageMetadata); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint) error); ok {
		r2 = returnFunc(ctx, id)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockObjectService_GetRawThumbnail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRawThumbnail'
type MockObjectService_GetRawThumbnail_Call struct {
	*mock.Call
}

// GetRawThumbnail is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockObjectService_Expecter) GetRawThumbnail(ctx any, id any) *MockObjectService_GetRawThumbnail_Call {
	return &MockObjectService_GetRawThumbnail_Call{Call: _e.mock.On("GetRawThumbnail", ctx, id)}
}

func (_c *MockObjectService_GetRawThumbnail_Call) Run(run func(ctx context.Context, id uint)) *MockObjectService_GetRawThumbnail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectService_GetRawThumbnail_Call) Return(reader io.ReadCloser, img *image.ImageMetadata, err error) *MockObjectService_GetRawThumbnail_Call {
	_c.Call.Return(reader, img, err)
	return _c
}

func (_c *MockObjectService_GetRawThumbnail_Call) RunAndReturn(run func(ctx context.Context, id uint) (io.ReadCloser, *image.ImageMetadata, error)) *MockObjectService_GetRawThumbnail_Call {
	_c.Call.Return(run)
	return _c
}

// GetRawThumbnailByHash provides a mock function for the type MockObjectService
func (_mock *MockObjectService) GetRawThumbnailByHash(ctx context.Context, hash string) (io.ReadCloser, *image.ImageMetadata, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetRawThumbnailByHash")
	}

	var r0 io.ReadCloser
	var r1 *image.ImageMetadata
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, *image.ImageMetadata, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *image.ImageMetadata); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, hash)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockObjectService_GetRawThumbnailByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRawThumbnailByHash'
type MockObjectService_GetRawThumbnailByHash_Call struct {
	*mock.Call
}

// GetRawThumbnailByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockObjectService_Expecter) GetRawThumbnailByHash(ctx any, hash any) *MockObjectService_GetRawThumbnailByHash_Call {
	return &MockObjectService_GetRawThumbnailByHash_Call{Call: _e.mock.On("GetRawThumbnailByHash", ctx, hash)}
}

func (_c *MockObjectService_GetRawThumbnailByHash_Call) Run(run func(ctx context.Context, hash string)) *MockObjectService_GetRawThumbnailByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectService_GetRawThumbnailByHash_Call) Return(reader io.ReadCloser, img *image.ImageMetadata, err error) *MockObjectService_GetRawThumbnailByHash_Call {
	_c.Call.Return(reader, img, err)
	return _c
}

func (_c *MockObjectService_GetRawThumbnailByHash_Call) RunAndReturn(run func(ctx context.Context, hash string) (io.ReadCloser, *image.ImageMetadata, error)) *MockObjectService_GetRawThumbnailByHash_Call {
	_c.Call.Return(run)
	return _c
}

// UploadImage provides a mock function for the type MockObjectService
func (_mock *MockObjectService) UploadImage(ctx context.Context, hash string, format image.Format, data []byte) error {
	ret := _mock.Called(ctx, hash, format, data)

	if len(ret) == 0 {
		panic("no return value specified for UploadImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, image.Format, []byte) error); ok {
		r0 = returnFunc(ctx, hash, format, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObjectService_UploadImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadImage'
type MockObjectService_UploadImage_Call struct {
	*mock.Call
}

// UploadImage is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
//   - format image.Format
//   - data []byte
func (_e *MockObjectService_Expecter) UploadImage(ctx any, hash any, format any, data any) *MockObjectService_UploadImage_Call {
	return &MockObjectService_UploadImage_Call{Call: _e.mock.On("UploadImage", ctx, hash, format, data)}
}

func (_c *MockObjectService_UploadImage_Call) Run(run func(ctx context.Context, hash string, format image.Format, data []byte)) *MockObjectService_UploadImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 image.Format
		if args[2] != nil {
			arg2 = args[2].(image.Format)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockObjectService_UploadImage_Call) Return(err error) *MockObjectService_UploadImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObjectService_UploadImage_Call) RunAndReturn(run func(ctx context.Context, hash string, format image.Format, data []byte) error) *MockObjectService_UploadImage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImageRepository creates a new instance of MockImageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageRepository {
	mock := &MockImageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageRepository is an autogenerated mock type for the ImageRepository type
type MockImageRepository struct {
	mock.Mock
}

type MockImageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageRepository) EXPECT() *MockImageRepository_Expecter {
	return &MockImageRepository_Expecter{mock: &_m.Mock}
}

// AttachTags provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) AttachTags(ctx context.Context, imageID uint, tags []tag.Tag) error {
	ret := _mock.Called(ctx, imageID, tags)

	if len(ret) == 0 {
		panic("no return value specified for AttachTags")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, []tag.Tag) error); ok {
		r0 = returnFunc(ctx, imageID, tags)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageRepository_AttachTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachTags'
type MockImageRepository_AttachTags_Call struct {
	*mock.Call
}

// AttachTags is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID uint
//   - tags []tag.Tag
func (_e *MockImageRepository_Expecter) AttachTags(ctx any, imageID any, tags any) *MockImageRepository_AttachTags_Call {
	return &MockImageRepository_AttachTags_Call{Call: _e.mock.On("AttachTags", ctx, imageID, tags)}
}

func (_c *MockImageRepository_AttachTags_Call) Run(run func(ctx context.Context, imageID uint, tags []tag.Tag)) *MockImageRepository_AttachTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 []tag.Tag
		if args[2] != nil {
			arg2 = args[2].([]tag.Tag)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageRepository_AttachTags_Call) Return(err error) *MockImageRepository_AttachTags_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageRepository_AttachTags_Call) RunAndReturn(run func(ctx context.Context, imageID uint, tags []tag.Tag) error) *MockImageRepository_AttachTags_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) Count(ctx context.Context, query *image.Query) (int64, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *image.Query) (int64, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *image.Query) int64); ok {
		r0 = returnFunc(ctx, query)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *image.Query) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockImageRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - query *image.Query
func (_e *MockImageRepository_Expecter) Count(ctx any, query any) *MockImageRepository_Count_Call {
	return &MockImageRepository_Count_Call{Call: _e.mock.On("Count", ctx, query)}
}

func (_c *MockImageRepository_Count_Call) Run(run func(ctx context.Context, query *image.Query)) *MockImageRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *image.Query
		if args[1] != nil {
			arg1 = args[1].(*image.Query)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_Count_Call) Return(n int64, err error) *MockImageRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockImageRepository_Count_Call) RunAndReturn(run func(ctx context.Context, query *image.Query) (int64, error)) *MockImageRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) Create(ctx context.Context, image1 *image.ImageMetadata) error {
	ret := _mock.Called(ctx, image1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *image.ImageMetadata) error); ok {
		r0 = returnFunc(ctx, image1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockImageRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - image1 *image.ImageMetadata
func (_e *MockImageRepository_Expecter) Create(ctx any, image1 any) *MockImageRepository_Create_Call {
	return &MockImageRepository_Create_Call{Call: _e.mock.On("Create", ctx, image1)}
}

func (_c *MockImageRepository_Create_Call) Run(run func(ctx context.Context, image1 *image.ImageMetadata)) *MockImageRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *image.ImageMetadata
		if args[1] != nil {
			arg1 = args[1].(*image.ImageMetadata)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_Create_Call) Return(err error) *MockImageRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageRepository_Create_Call) RunAndReturn(run func(ctx context.Context, image1 *image.ImageMetadata) error) *MockImageRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) Delete(ctx context.Context, id uint) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockImageRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockImageRepository_Expecter) Delete(ctx any, id any) *MockImageRepository_Delete_Call {
	return &MockImageRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockImageRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockImageRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_Delete_Call) Return(err error) *MockImageRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uint) error) *MockImageRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByIDs provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) DeleteByIDs(ctx context.Context, ids []uint) error {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByIDs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageRepository_DeleteByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByIDs'
type MockImageRepository_DeleteByIDs_Call struct {
	*mock.Call
}

// DeleteByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uint
func (_e *MockImageRepository_Expecter) DeleteByIDs(ctx any, ids any) *MockImageRepository_DeleteByIDs_Call {
	return &MockImageRepository_DeleteByIDs_Call{Call: _e.mock.On("DeleteByIDs", ctx, ids)}
}

func (_c *MockImageRepository_DeleteByIDs_Call) Run(run func(ctx context.Context, ids []uint)) *MockImageRepository_DeleteByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uint
		if args[1] != nil {
			arg1 = args[1].([]uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_DeleteByIDs_Call) Return(err error) *MockImageRepository_DeleteByIDs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageRepository_DeleteByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []uint) error) *MockImageRepository_DeleteByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByHash provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) ExistsByHash(ctx context.Context, hash string) (bool, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByHash")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_ExistsByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByHash'
type MockImageRepository_ExistsByHash_Call struct {
	*mock.Call
}

// ExistsByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockImageRepository_Expecter) ExistsByHash(ctx any, hash any) *MockImageRepository_ExistsByHash_Call {
	return &MockImageRepository_ExistsByHash_Call{Call: _e.mock.On("ExistsByHash", ctx, hash)}
}

func (_c *MockImageRepository_ExistsByHash_Call) Run(run func(ctx context.Context, hash string)) *MockImageRepository_ExistsByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_ExistsByHash_Call) Return(b bool, err error) *MockImageRepository_ExistsByHash_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockImageRepository_ExistsByHash_Call) RunAndReturn(run func(ctx context.Context, hash string) (bool, error)) *MockImageRepository_ExistsByHash_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByName provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) ExistsByName(ctx context.Context, name string) (bool, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByName")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_ExistsByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByName'
type MockImageRepository_ExistsByName_Call struct {
	*mock.Call
}

// ExistsByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockImageRepository_Expecter) ExistsByName(ctx any, name any) *MockImageRepository_ExistsByName_Call {
	return &MockImageRepository_ExistsByName_Call{Call: _e.mock.On("ExistsByName", ctx, name)}
}

func (_c *MockImageRepository_ExistsByName_Call) Run(run func(ctx context.Context, name string)) *MockImageRepository_ExistsByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_ExistsByName_Call) Return(b bool, err error) *MockImageRepository_ExistsByName_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockImageRepository_ExistsByName_Call) RunAndReturn(run func(ctx context.Context, name string) (bool, error)) *MockImageRepository_ExistsByName_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) Get(ctx context.Context, id uint) (*image.ImageMetadata, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *image.ImageMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*image.ImageMetadata, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *image.ImageMetadata); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockImageRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockImageRepository_Expecter) Get(ctx any, id any) *MockImageRepository_Get_Call {
	return &MockImageRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockImageRepository_Get_Call) Run(run func(ctx context.Context, id uint)) *MockImageRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_Get_Call) Return(imageMetadata *image.ImageMetadata, err error) *MockImageRepository_Get_Call {
	_c.Call.Return(imageMetadata, err)
	return _c
}

func (_c *MockImageRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id uint) (*image.ImageMetadata, error)) *MockImageRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByHash provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) GetByHash(ctx context.Context, hash string) (*image.ImageMetadata, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetByHash")
	}

	var r0 *image.ImageMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*image.ImageMetadata, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *image.ImageMetadata); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_GetByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHash'
type MockImageRepository_GetByHash_Call struct {
	*mock.Call
}

// GetByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockImageRepository_Expecter) GetByHash(ctx any, hash any) *MockImageRepository_GetByHash_Call {
	return &MockImageRepository_GetByHash_Call{Call: _e.mock.On("GetByHash", ctx, hash)}
}

func (_c *MockImageRepository_GetByHash_Call) Run(run func(ctx context.Context, hash string)) *MockImageRepository_GetByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_GetByHash_Call) Return(imageMetadata *image.ImageMetadata, err error) *MockImageRepository_GetByHash_Call {
	_c.Call.Return(imageMetadata, err)
	return _c
}

func (_c *MockImageRepository_GetByHash_Call) RunAndReturn(run func(ctx context.Context, hash string) (*image.ImageMetadata, error)) *MockImageRepository_GetByHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) GetByName(ctx context.Context, name string) (*image.ImageMetadata, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *image.ImageMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*image.ImageMetadata, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *image.ImageMetadata); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockImageRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockImageRepository_Expecter) GetByName(ctx any, name any) *MockImageRepository_GetByName_Call {
	return &MockImageRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockImageRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockImageRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_GetByName_Call) Return(imageMetadata *image.ImageMetadata, err error) *MockImageRepository_GetByName_Call {
	_c.Call.Return(imageMetadata, err)
	return _c
}

func (_c *MockImageRepository_GetByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*image.ImageMetadata, error)) *MockImageRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceTags provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) ReplaceTags(ctx context.Context, imageID uint, tags []tag.Tag) error {
	ret := _mock.Called(ctx, imageID, tags)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceTags")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, []tag.Tag) error); ok {
		r0 = returnFunc(ctx, imageID, tags)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageRepository_ReplaceTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceTags'
type MockImageRepository_ReplaceTags_Call struct {
	*mock.Call
}

// ReplaceTags is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID uint
//   - tags []tag.Tag
func (_e *MockImageRepository_Expecter) ReplaceTags(ctx any, imageID any, tags any) *MockImageRepository_ReplaceTags_Call {
	return &MockImageRepository_ReplaceTags_Call{Call: _e.mock.On("ReplaceTags", ctx, imageID, tags)}
}

func (_c *MockImageRepository_ReplaceTags_Call) Run(run func(ctx context.Context, imageID uint, tags []tag.Tag)) *MockImageRepository_ReplaceTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 []tag.Tag
		if args[2] != nil {
			arg2 = args[2].([]tag.Tag)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageRepository_ReplaceTags_Call) Return(err error) *MockImageRepository_ReplaceTags_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageRepository_ReplaceTags_Call) RunAndReturn(run func(ctx context.Context, imageID uint, tags []tag.Tag) error) *MockImageRepository_ReplaceTags_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) Search(ctx context.Context, query *image.Query) ([]image.ImageMetadata, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []image.ImageMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *image.Query) ([]image.ImageMetadata, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *image.Query) []image.ImageMetadata); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *image.Query) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockImageRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query *image.Query
func (_e *MockImageRepository_Expecter) Search(ctx any, query any) *MockImageRepository_Search_Call {
	return &MockImageRepository_Search_Call{Call: _e.mock.On("Search", ctx, query)}
}

func (_c *MockImageRepository_Search_Call) Run(run func(ctx context.Context, query *image.Query)) *MockImageRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *image.Query
		if args[1] != nil {
			arg1 = args[1].(*image.Query)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_Search_Call) Return(imageMetadatas []image.ImageMetadata, err error) *MockImageRepository_Search_Call {
	_c.Call.Return(imageMetadatas, err)
	return _c
}

func (_c *MockImageRepository_Search_Call) RunAndReturn(run func(ctx context.Context, query *image.Query) ([]image.ImageMetadata, error)) *MockImageRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) Update(ctx context.Context, image1 *image.ImageMetadata) error {
	ret := _mock.Called(ctx, image1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *image.ImageMetadata) error); ok {
		r0 = returnFunc(ctx, image1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockImageRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - image1 *image.ImageMetadata
func (_e *MockImageRepository_Expecter) Update(ctx any, image1 any) *MockImageRepository_Update_Call {
	return &MockImageRepository_Update_Call{Call: _e.mock.On("Update", ctx, image1)}
}

func (_c *MockImageRepository_Update_Call) Run(run func(ctx context.Context, image1 *image.ImageMetadata)) *MockImageRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *image.ImageMetadata
		if args[1] != nil {
			arg1 = args[1].(*image.ImageMetadata)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_Update_Call) Return(err error) *MockImageRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageRepository_Update_Call) RunAndReturn(run func(ctx context.Context, image1 *image.ImageMetadata) error) *MockImageRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) WithTx(tx *gorm.DB) image.ImageRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 image.ImageRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) image.ImageRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(image.ImageRepository)
		}
	}
	return r0
}

// MockImageRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockImageRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockImageRepository_Expecter) WithTx(tx any) *MockImageRepository_WithTx_Call {
	return &MockImageRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockImageRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockImageRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageRepository_WithTx_Call) Return(imageRepository image.ImageRepository) *MockImageRepository_WithTx_Call {
	_c.Call.Return(imageRepository)
	return _c
}

func (_c *MockImageRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) image.ImageRepository) *MockImageRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImageService creates a new instance of MockImageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageService {
	mock := &MockImageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageService is an autogenerated mock type for the ImageService type
type MockImageService struct {
	mock.Mock
}

type MockImageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageService) EXPECT() *MockImageService_Expecter {
	return &MockImageService_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockImageService
func (_mock *MockImageService) Count(ctx context.Context, query *image.Query) (int64, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *image.Query) (int64, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *image.Query) int64); ok {
		r0 = returnFunc(ctx, query)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *image.Query) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageService_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockImageService_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - query *image.Query
func (_e *MockImageService_Expecter) Count(ctx any, query any) *MockImageService_Count_Call {
	return &MockImageService_Count_Call{Call: _e.mock.On("Count", ctx, query)}
}

func (_c *MockImageService_Count_Call) Run(run func(ctx context.Context, query *image.Query)) *MockImageService_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *image.Query
		if args[1] != nil {
			arg1 = args[1].(*image.Query)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageService_Count_Call) Return(n int64, err error) *MockImageService_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockImageService_Count_Call) RunAndReturn(run func(ctx context.Context, query *image.Query) (int64, error)) *MockImageService_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockImageService
func (_mock *MockImageService) Delete(ctx context.Context, userID uint, id uint) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockImageService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - id uint
func (_e *MockImageService_Expecter) Delete(ctx any, userID any, id any) *MockImageService_Delete_Call {
	return &MockImageService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *MockImageService_Delete_Call) Run(run func(ctx context.Context, userID uint, id uint)) *MockImageService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageService_Delete_Call) Return(err error) *MockImageService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageService_Delete_Call) RunAndReturn(run func(ctx context.Context, userID uint, id uint) error) *MockImageService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByName provides a mock function for the type MockImageService
func (_mock *MockImageService) DeleteByName(ctx context.Context, userID uint, name string) error {
	ret := _mock.Called(ctx, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = returnFunc(ctx, userID, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageService_DeleteByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByName'
type MockImageService_DeleteByName_Call struct {
	*mock.Call
}

// DeleteByName is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - name string
func (_e *MockImageService_Expecter) DeleteByName(ctx any, userID any, name any) *MockImageService_DeleteByName_Call {
	return &MockImageService_DeleteByName_Call{Call: _e.mock.On("DeleteByName", ctx, userID, name)}
}

func (_c *MockImageService_DeleteByName_Call) Run(run func(ctx context.Context, userID uint, name string)) *MockImageService_DeleteByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageService_DeleteByName_Call) Return(err error) *MockImageService_DeleteByName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageService_DeleteByName_Call) RunAndReturn(run func(ctx context.Context, userID uint, name string) error) *MockImageService_DeleteByName_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByQuery provides a mock function for the type MockImageService
func (_mock *MockImageService) DeleteByQuery(ctx context.Context, userID uint, query *image.Query) []error {
	ret := _mock.Called(ctx, userID, query)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByQuery")
	}

	var r0 []error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, *image.Query) []error); ok {
		r0 = returnFunc(ctx, userID, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}
	return r0
}

// MockImageService_DeleteByQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByQuery'
type MockImageService_DeleteByQuery_Call struct {
	*mock.Call
}

// DeleteByQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - query *image.Query
func (_e *MockImageService_Expecter) DeleteByQuery(ctx any, userID any, query any) *MockImageService_DeleteByQuery_Call {
	return &MockImageService_DeleteByQuery_Call{Call: _e.mock.On("DeleteByQuery", ctx, userID, query)}
}

func (_c *MockImageService_DeleteByQuery_Call) Run(run func(ctx context.Context, userID uint, query *image.Query)) *MockImageService_DeleteByQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 *image.Query
		if args[2] != nil {
			arg2 = args[2].(*image.Query)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageService_DeleteByQuery_Call) Return(errs []error) *MockImageService_DeleteByQuery_Call {
	_c.Call.Return(errs)
	return _c
}

func (_c *MockImageService_DeleteByQuery_Call) RunAndReturn(run func(ctx context.Context, userID uint, query *image.Query) []error) *MockImageService_DeleteByQuery_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByHash provides a mock function for the type MockImageService
func (_mock *MockImageService) ExistsByHash(ctx context.Context, hash string) (bool, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByHash")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageService_ExistsByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByHash'
type MockImageService_ExistsByHash_Call struct {
	*mock.Call
}

// ExistsByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockImageService_Expecter) ExistsByHash(ctx any, hash any) *MockImageService_ExistsByHash_Call {
	return &MockImageService_ExistsByHash_Call{Call: _e.mock.On("ExistsByHash", ctx, hash)}
}

func (_c *MockImageService_ExistsByHash_Call) Run(run func(ctx context.Context, hash string)) *MockImageService_ExistsByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageService_ExistsByHash_Call) Return(b bool, err error) *MockImageService_ExistsByHash_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockImageService_ExistsByHash_Call) RunAndReturn(run func(ctx context.Context, hash string) (bool, error)) *MockImageService_ExistsByHash_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByName provides a mock function for the type MockImageService
func (_mock *MockImageService) ExistsByName(ctx context.Context, name string) (bool, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByName")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageService_ExistsByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByName'
type MockImageService_ExistsByName_Call struct {
	*mock.Call
}

// ExistsByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockImageService_Expecter) ExistsByName(ctx any, name any) *MockImageService_ExistsByName_Call {
	return &MockImageService_ExistsByName_Call{Call: _e.mock.On("ExistsByName", ctx, name)}
}

func (_c *MockImageService_ExistsByName_Call) Run(run func(ctx context.Context, name string)) *MockImageService_ExistsByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageService_ExistsByName_Call) Return(b bool, err error) *MockImageService_ExistsByName_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockImageService_ExistsByName_Call) RunAndReturn(run func(ctx context.Context, name string) (bool, error)) *MockImageService_ExistsByName_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockImageService
func (_mock *MockImageService) Get(ctx context.Context, id uint) (*image.ImageMetadata, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *image.ImageMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*image.ImageMetadata, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *image.ImageMetadata); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockImageService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockImageService_Expecter) Get(ctx any, id any) *MockImageService_Get_Call {
	return &MockImageService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockImageService_Get_Call) Run(run func(ctx context.Context, id uint)) *MockImageService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageService_Get_Call) Return(imageMetadata *image.ImageMetadata, err error) *MockImageService_Get_Call {
	_c.Call.Return(imageMetadata, err)
	return _c
}

func (_c *MockImageService_Get_Call) RunAndReturn(run func(ctx context.Context, id uint) (*image.ImageMetadata, error)) *MockImageService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByHash provides a mock function for the type MockImageService
func (_mock *MockImageService) GetByHash(ctx context.Context, hash string) (*image.ImageMetadata, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetByHash")
	}

	var r0 *image.ImageMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*image.ImageMetadata, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *image.ImageMetadata); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageService_GetByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHash'
type MockImageService_GetByHash_Call struct {
	*mock.Call
}

// GetByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockImageService_Expecter) GetByHash(ctx any, hash any) *MockImageService_GetByHash_Call {
	return &MockImageService_GetByHash_Call{Call: _e.mock.On("GetByHash", ctx, hash)}
}

func (_c *MockImageService_GetByHash_Call) Run(run func(ctx context.Context, hash string)) *MockImageService_GetByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageService_GetByHash_Call) Return(imageMetadata *image.ImageMetadata, err error) *MockImageService_GetByHash_Call {
	_c.Call.Return(imageMetadata, err)
	return _c
}

func (_c *MockImageService_GetByHash_Call) RunAndReturn(run func(ctx context.Context, hash string) (*image.ImageMetadata, error)) *MockImageService_GetByHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type MockImageService
func (_mock *MockImageService) GetByName(ctx context.Context, name string) (*image.ImageMetadata, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *image.ImageMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*image.ImageMetadata, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *image.ImageMetadata); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageService_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockImageService_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockImageService_Expecter) GetByName(ctx any, name any) *MockImageService_GetByName_Call {
	return &MockImageService_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockImageService_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockImageService_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageService_GetByName_Call) Return(imageMetadata *image.ImageMetadata, err error) *MockImageService_GetByName_Call {
	_c.Call.Return(imageMetadata, err)
	return _c
}

func (_c *MockImageService_GetByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*image.ImageMetadata, error)) *MockImageService_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockImageService
func (_mock *MockImageService) Search(ctx context.Context, query *image.Query) ([]image.ImageMetadata, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []image.ImageMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *image.Query) ([]image.ImageMetadata, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *image.Query) []image.ImageMetadata); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *image.Query) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockImageService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query *image.Query
func (_e *MockImageService_Expecter) Search(ctx any, query any) *MockImageService_Search_Call {
	return &MockImageService_Search_Call{Call: _e.mock.On("Search", ctx, query)}
}

func (_c *MockImageService_Search_Call) Run(run func(ctx context.Context, query *image.Query)) *MockImageService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *image.Query
		if args[1] != nil {
			arg1 = args[1].(*image.Query)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageService_Search_Call) Return(imageMetadatas []image.ImageMetadata, err error) *MockImageService_Search_Call {
	_c.Call.Return(imageMetadatas, err)
	return _c
}

func (_c *MockImageService_Search_Call) RunAndReturn(run func(ctx context.Context, query *image.Query) ([]image.ImageMetadata, error)) *MockImageService_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockImageService
func (_mock *MockImageService) Update(ctx context.Context, userID uint, imageID uint, image1 *image.ImagePatchRequest) (*image.ImageMetadata, error) {
	ret := _mock.Called(ctx, userID, imageID, image1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *image.ImageMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, *image.ImagePatchRequest) (*image.ImageMetadata, error)); ok {
		return returnFunc(ctx, userID, imageID, image1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, *image.ImagePatchRequest) *image.ImageMetadata); ok {
		r0 = returnFunc(ctx, userID, imageID, image1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint, *image.ImagePatchRequest) error); ok {
		r1 = returnFunc(ctx, userID, imageID, image1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockImageService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - imageID uint
//   - image1 *image.ImagePatchRequest
func (_e *MockImageService_Expecter) Update(ctx any, userID any, imageID any, image1 any) *MockImageService_Update_Call {
	return &MockImageService_Update_Call{Call: _e.mock.On("Update", ctx, userID, imageID, image1)}
}

func (_c *MockImageService_Update_Call) Run(run func(ctx context.Context, userID uint, imageID uint, image1 *image.ImagePatchRequest)) *MockImageService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 *image.ImagePatchRequest
		if args[3] != nil {
			arg3 = args[3].(*image.ImagePatchRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockImageService_Update_Call) Return(imageMetadata *image.ImageMetadata, err error) *MockImageService_Update_Call {
	_c.Call.Return(imageMetadata, err)
	return _c
}

func (_c *MockImageService_Update_Call) RunAndReturn(run func(ctx context.Context, userID uint, imageID uint, image1 *image.ImagePatchRequest) (*image.ImageMetadata, error)) *MockImageService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockImageService
func (_mock *MockImageService) Upload(ctx context.Context, userID uint, req image.UploadRequest, format image.Format, data []byte) (*image.ImageMetadata, error) {
	ret := _mock.Called(ctx, userID, req, format, data)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 *image.ImageMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, image.UploadRequest, image.Format, []byte) (*image.ImageMetadata, error)); ok {
		return returnFunc(ctx, userID, req, format, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, image.UploadRequest, image.Format, []byte) *image.ImageMetadata); ok {
		r0 = returnFunc(ctx, userID, req, format, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*image.ImageMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, image.UploadRequest, image.Format, []byte) error); ok {
		r1 = returnFunc(ctx, userID, req, format, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageService_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockImageService_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - req image.UploadRequest
//   - format image.Format
//   - data []byte
func (_e *MockImageService_Expecter) Upload(ctx any, userID any, req any, format any, data any) *MockImageService_Upload_Call {
	return &MockImageService_Upload_Call{Call: _e.mock.On("Upload", ctx, userID, req, format, data)}
}

func (_c *MockImageService_Upload_Call) Run(run func(ctx context.Context, userID uint, req image.UploadRequest, format image.Format, data []byte)) *MockImageService_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 image.UploadRequest
		if args[2] != nil {
			arg2 = args[2].(image.UploadRequest)
		}
		var arg3 image.Format
		if args[3] != nil {
			arg3 = args[3].(image.Format)
		}
		var arg4 []byte
		if args[4] != nil {
			arg4 = args[4].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockImageService_Upload_Call) Return(imageMetadata *image.ImageMetadata, err error) *MockImageService_Upload_Call {
	_c.Call.Return(imageMetadata, err)
	return _c
}

func (_c *MockImageService_Upload_Call) RunAndReturn(run func(ctx context.Context, userID uint, req image.UploadRequest, format image.Format, data []byte) (*image.ImageMetadata, error)) *MockImageService_Upload_Call {
	_c.Call.Return(run)
	return _c
}
