// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package log

import (
	"server/internal/log"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockLogRepository creates a new instance of MockLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogRepository {
	mock := &MockLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogRepository is an autogenerated mock type for the LogRepository type
type MockLogRepository struct {
	mock.Mock
}

type MockLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogRepository) EXPECT() *MockLogRepository_Expecter {
	return &MockLogRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockLogRepository
func (_mock *MockLogRepository) Create(entry *log.AuditEntry) error {
	ret := _mock.Called(entry)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*log.AuditEntry) error); ok {
		r0 = returnFunc(entry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLogRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLogRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - entry *log.AuditEntry
func (_e *MockLogRepository_Expecter) Create(entry any) *MockLogRepository_Create_Call {
	return &MockLogRepository_Create_Call{Call: _e.mock.On("Create", entry)}
}

func (_c *MockLogRepository_Create_Call) Run(run func(entry *log.AuditEntry)) *MockLogRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *log.AuditEntry
		if args[0] != nil {
			arg0 = args[0].(*log.AuditEntry)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLogRepository_Create_Call) Return(err error) *MockLogRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLogRepository_Create_Call) RunAndReturn(run func(entry *log.AuditEntry) error) *MockLogRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntries provides a mock function for the type MockLogRepository
func (_mock *MockLogRepository) GetEntries(cursor int, limit int) ([]log.AuditEntry, error) {
	ret := _mock.Called(cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetEntries")
	}

	var r0 []log.AuditEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]log.AuditEntry, error)); ok {
		return returnFunc(cursor, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []log.AuditEntry); ok {
		r0 = returnFunc(cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]log.AuditEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = returnFunc(cursor, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLogRepository_GetEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntries'
type MockLogRepository_GetEntries_Call struct {
	*mock.Call
}

// GetEntries is a helper method to define mock.On call
//   - cursor int
//   - limit int
func (_e *MockLogRepository_Expecter) GetEntries(cursor any, limit any) *MockLogRepository_GetEntries_Call {
	return &MockLogRepository_GetEntries_Call{Call: _e.mock.On("GetEntries", cursor, limit)}
}

func (_c *MockLogRepository_GetEntries_Call) Run(run func(cursor int, limit int)) *MockLogRepository_GetEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLogRepository_GetEntries_Call) Return(auditEntrys []log.AuditEntry, err error) *MockLogRepository_GetEntries_Call {
	_c.Call.Return(auditEntrys, err)
	return _c
}

func (_c *MockLogRepository_GetEntries_Call) RunAndReturn(run func(cursor int, limit int) ([]log.AuditEntry, error)) *MockLogRepository_GetEntries_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockLogRepository
func (_mock *MockLogRepository) WithTx(tx *gorm.DB) log.LogRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 log.LogRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) log.LogRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.LogRepository)
		}
	}
	return r0
}

// MockLogRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockLogRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockLogRepository_Expecter) WithTx(tx any) *MockLogRepository_WithTx_Call {
	return &MockLogRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockLogRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockLogRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLogRepository_WithTx_Call) Return(logRepository log.LogRepository) *MockLogRepository_WithTx_Call {
	_c.Call.Return(logRepository)
	return _c
}

func (_c *MockLogRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) log.LogRepository) *MockLogRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogService creates a new instance of MockLogService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogService {
	mock := &MockLogService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogService is an autogenerated mock type for the LogService type
type MockLogService struct {
	mock.Mock
}

type MockLogService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogService) EXPECT() *MockLogService_Expecter {
	return &MockLogService_Expecter{mock: &_m.Mock}
}

// GetEntries provides a mock function for the type MockLogService
func (_mock *MockLogService) GetEntries(cursor int, limit int) ([]log.EntryResponse, error) {
	ret := _mock.Called(cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetEntries")
	}

	var r0 []log.EntryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]log.EntryResponse, error)); ok {
		return returnFunc(cursor, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []log.EntryResponse); ok {
		r0 = returnFunc(cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]log.EntryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = returnFunc(cursor, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLogService_GetEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntries'
type MockLogService_GetEntries_Call struct {
	*mock.Call
}

// GetEntries is a helper method to define mock.On call
//   - cursor int
//   - limit int
func (_e *MockLogService_Expecter) GetEntries(cursor any, limit any) *MockLogService_GetEntries_Call {
	return &MockLogService_GetEntries_Call{Call: _e.mock.On("GetEntries", cursor, limit)}
}

func (_c *MockLogService_GetEntries_Call) Run(run func(cursor int, limit int)) *MockLogService_GetEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLogService_GetEntries_Call) Return(entryResponses []log.EntryResponse, err error) *MockLogService_GetEntries_Call {
	_c.Call.Return(entryResponses, err)
	return _c
}

func (_c *MockLogService_GetEntries_Call) RunAndReturn(run func(cursor int, limit int) ([]log.EntryResponse, error)) *MockLogService_GetEntries_Call {
	_c.Call.Return(run)
	return _c
}

// Log provides a mock function for the type MockLogService
func (_mock *MockLogService) Log(tx *gorm.DB, action string, objectType string, userID uint, objectID uint, data any) error {
	ret := _mock.Called(tx, action, objectType, userID, objectID, data)

	if len(ret) == 0 {
		panic("no return value specified for Log")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, string, string, uint, uint, any) error); ok {
		r0 = returnFunc(tx, action, objectType, userID, objectID, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLogService_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type MockLogService_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//   - tx *gorm.DB
//   - action string
//   - objectType string
//   - userID uint
//   - objectID uint
//   - data any
func (_e *MockLogService_Expecter) Log(tx any, action any, objectType any, userID any, objectID any, data any) *MockLogService_Log_Call {
	return &MockLogService_Log_Call{Call: _e.mock.On("Log", tx, action, objectType, userID, objectID, data)}
}

func (_c *MockLogService_Log_Call) Run(run func(tx *gorm.DB, action string, objectType string, userID uint, objectID uint, data any)) *MockLogService_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 uint
		if args[3] != nil {
			arg3 = args[3].(uint)
		}
		var arg4 uint
		if args[4] != nil {
			arg4 = args[4].(uint)
		}
		var arg5 any
		if args[5] != nil {
			arg5 = args[5].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockLogService_Log_Call) Return(err error) *MockLogService_Log_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLogService_Log_Call) RunAndReturn(run func(tx *gorm.DB, action string, objectType string, userID uint, objectID uint, data any) error) *MockLogService_Log_Call {
	_c.Call.Return(run)
	return _c
}
