definitions:
  main.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  main.authRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: kartonko web server
  title: kartonko API
  version: "1.0"
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Logs in a user, generating a JWT token.
      parameters:
      - description: username and password
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.authRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Login a user
      tags:
      - Auth
  /api/v1/auth/logout:
    post:
      consumes:
      - application/json
      description: Logs out a user, deleting the JWT token.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Logout a user
      tags:
      - Auth
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Registers a new user, generating a JWT token.
      parameters:
      - description: username and password
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.authRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Register a user
      tags:
      - Auth
  /api/v1/image/{name}:
    get:
      consumes:
      - application/json
      description: Searches images by unique name
      parameters:
      - description: name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      - ' application/octet-stream'
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Searches image by name
      tags:
      - Image
  /api/v1/images/{range}:
    get:
      consumes:
      - application/json
      description: Gets images from a global list by range
      parameters:
      - description: start-end
        in: query
        name: range
        required: true
        type: string
      produces:
      - application/json
      - ' application/octet-stream'
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Gets images by range
      tags:
      - Image
  /api/v1/search-tags/{query}:
    get:
      consumes:
      - application/json
      description: Searches all matching tags
      parameters:
      - description: search-query
        in: query
        name: query
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Searches tags
      tags:
      - Tags
  /api/v1/upload:
    post:
      consumes:
      - application/json
      - ' multipart/form-data'
      description: Uploads image, name and hash must be unique
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      security:
      - BearerToken: []
      summary: Uploads image
      tags:
      - Image
securityDefinitions:
  BearerAuth:
    in: cookie
    name: jwt
    type: apiKey
swagger: "2.0"
