// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	"context"
	"server/internal/user"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Create(ctx context.Context, user1 *user.User) error {
	ret := _mock.Called(ctx, user1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.User) error); ok {
		r0 = returnFunc(ctx, user1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user1 *user.User
func (_e *MockUserRepository_Expecter) Create(ctx any, user1 any) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, user1)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(ctx context.Context, user1 *user.User)) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.User
		if args[1] != nil {
			arg1 = args[1].(*user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(err error) *MockUserRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(ctx context.Context, user1 *user.User) error) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Delete(ctx context.Context, userID uint) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockUserRepository_Expecter) Delete(ctx any, userID any) *MockUserRepository_Delete_Call {
	return &MockUserRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, userID)}
}

func (_c *MockUserRepository_Delete_Call) Run(run func(ctx context.Context, userID uint)) *MockUserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Delete_Call) Return(err error) *MockUserRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, userID uint) error) *MockUserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByEmail provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByEmail")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_ExistsByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByEmail'
type MockUserRepository_ExistsByEmail_Call struct {
	*mock.Call
}

// ExistsByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepository_Expecter) ExistsByEmail(ctx any, email any) *MockUserRepository_ExistsByEmail_Call {
	return &MockUserRepository_ExistsByEmail_Call{Call: _e.mock.On("ExistsByEmail", ctx, email)}
}

func (_c *MockUserRepository_ExistsByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_ExistsByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_ExistsByEmail_Call) Return(b bool, err error) *MockUserRepository_ExistsByEmail_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserRepository_ExistsByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (bool, error)) *MockUserRepository_ExistsByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByUsername provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) ExistsByUsername(ctx context.Context, username string) (bool, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByUsername")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_ExistsByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByUsername'
type MockUserRepository_ExistsByUsername_Call struct {
	*mock.Call
}

// ExistsByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserRepository_Expecter) ExistsByUsername(ctx any, username any) *MockUserRepository_ExistsByUsername_Call {
	return &MockUserRepository_ExistsByUsername_Call{Call: _e.mock.On("ExistsByUsername", ctx, username)}
}

func (_c *MockUserRepository_ExistsByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserRepository_ExistsByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_ExistsByUsername_Call) Return(b bool, err error) *MockUserRepository_ExistsByUsername_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserRepository_ExistsByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (bool, error)) *MockUserRepository_ExistsByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Get(ctx context.Context, id uint) (*user.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*user.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *user.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUserRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockUserRepository_Expecter) Get(ctx any, id any) *MockUserRepository_Get_Call {
	return &MockUserRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockUserRepository_Get_Call) Run(run func(ctx context.Context, id uint)) *MockUserRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Get_Call) Return(user1 *user.User, err error) *MockUserRepository_Get_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id uint) (*user.User, error)) *MockUserRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetByEmail(ctx context.Context, email string) (*user.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockUserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepository_Expecter) GetByEmail(ctx any, email any) *MockUserRepository_GetByEmail_Call {
	return &MockUserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockUserRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetByEmail_Call) Return(user1 *user.User, err error) *MockUserRepository_GetByEmail_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepository_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*user.User, error)) *MockUserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByProviderID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetByProviderID(ctx context.Context, providerID string) (*user.User, error) {
	ret := _mock.Called(ctx, providerID)

	if len(ret) == 0 {
		panic("no return value specified for GetByProviderID")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return returnFunc(ctx, providerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = returnFunc(ctx, providerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, providerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetByProviderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByProviderID'
type MockUserRepository_GetByProviderID_Call struct {
	*mock.Call
}

// GetByProviderID is a helper method to define mock.On call
//   - ctx context.Context
//   - providerID string
func (_e *MockUserRepository_Expecter) GetByProviderID(ctx any, providerID any) *MockUserRepository_GetByProviderID_Call {
	return &MockUserRepository_GetByProviderID_Call{Call: _e.mock.On("GetByProviderID", ctx, providerID)}
}

func (_c *MockUserRepository_GetByProviderID_Call) Run(run func(ctx context.Context, providerID string)) *MockUserRepository_GetByProviderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetByProviderID_Call) Return(user1 *user.User, err error) *MockUserRepository_GetByProviderID_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepository_GetByProviderID_Call) RunAndReturn(run func(ctx context.Context, providerID string) (*user.User, error)) *MockUserRepository_GetByProviderID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsername provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetByUsername(ctx context.Context, username string) (*user.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type MockUserRepository_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserRepository_Expecter) GetByUsername(ctx any, username any) *MockUserRepository_GetByUsername_Call {
	return &MockUserRepository_GetByUsername_Call{Call: _e.mock.On("GetByUsername", ctx, username)}
}

func (_c *MockUserRepository_GetByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserRepository_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetByUsername_Call) Return(user1 *user.User, err error) *MockUserRepository_GetByUsername_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepository_GetByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*user.User, error)) *MockUserRepository_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// SetPrivilege provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) SetPrivilege(ctx context.Context, userID uint, privilege user.Privilege) error {
	ret := _mock.Called(ctx, userID, privilege)

	if len(ret) == 0 {
		panic("no return value specified for SetPrivilege")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, user.Privilege) error); ok {
		r0 = returnFunc(ctx, userID, privilege)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_SetPrivilege_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPrivilege'
type MockUserRepository_SetPrivilege_Call struct {
	*mock.Call
}

// SetPrivilege is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - privilege user.Privilege
func (_e *MockUserRepository_Expecter) SetPrivilege(ctx any, userID any, privilege any) *MockUserRepository_SetPrivilege_Call {
	return &MockUserRepository_SetPrivilege_Call{Call: _e.mock.On("SetPrivilege", ctx, userID, privilege)}
}

func (_c *MockUserRepository_SetPrivilege_Call) Run(run func(ctx context.Context, userID uint, privilege user.Privilege)) *MockUserRepository_SetPrivilege_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 user.Privilege
		if args[2] != nil {
			arg2 = args[2].(user.Privilege)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_SetPrivilege_Call) Return(err error) *MockUserRepository_SetPrivilege_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_SetPrivilege_Call) RunAndReturn(run func(ctx context.Context, userID uint, privilege user.Privilege) error) *MockUserRepository_SetPrivilege_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Update(ctx context.Context, user1 *user.User) error {
	ret := _mock.Called(ctx, user1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.User) error); ok {
		r0 = returnFunc(ctx, user1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user1 *user.User
func (_e *MockUserRepository_Expecter) Update(ctx any, user1 any) *MockUserRepository_Update_Call {
	return &MockUserRepository_Update_Call{Call: _e.mock.On("Update", ctx, user1)}
}

func (_c *MockUserRepository_Update_Call) Run(run func(ctx context.Context, user1 *user.User)) *MockUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.User
		if args[1] != nil {
			arg1 = args[1].(*user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Update_Call) Return(err error) *MockUserRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_Update_Call) RunAndReturn(run func(ctx context.Context, user1 *user.User) error) *MockUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) WithTx(tx *gorm.DB) user.UserRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 user.UserRepository
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) user.UserRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(user.UserRepository)
		}
	}
	return r0
}

// MockUserRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockUserRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockUserRepository_Expecter) WithTx(tx any) *MockUserRepository_WithTx_Call {
	return &MockUserRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockUserRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockUserRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_WithTx_Call) Return(userRepository user.UserRepository) *MockUserRepository_WithTx_Call {
	_c.Call.Return(userRepository)
	return _c
}

func (_c *MockUserRepository_WithTx_Call) RunAndReturn(run func(tx *gorm.DB) user.UserRepository) *MockUserRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserService
func (_mock *MockUserService) Create(ctx context.Context, user1 *user.User) error {
	ret := _mock.Called(ctx, user1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.User) error); ok {
		r0 = returnFunc(ctx, user1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user1 *user.User
func (_e *MockUserService_Expecter) Create(ctx any, user1 any) *MockUserService_Create_Call {
	return &MockUserService_Create_Call{Call: _e.mock.On("Create", ctx, user1)}
}

func (_c *MockUserService_Create_Call) Run(run func(ctx context.Context, user1 *user.User)) *MockUserService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.User
		if args[1] != nil {
			arg1 = args[1].(*user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_Create_Call) Return(err error) *MockUserService_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_Create_Call) RunAndReturn(run func(ctx context.Context, user1 *user.User) error) *MockUserService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateByGoogle provides a mock function for the type MockUserService
func (_mock *MockUserService) CreateByGoogle(ctx context.Context, username string, email string, googleID string, pictureURL string) (*user.User, error) {
	ret := _mock.Called(ctx, username, email, googleID, pictureURL)

	if len(ret) == 0 {
		panic("no return value specified for CreateByGoogle")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*user.User, error)); ok {
		return returnFunc(ctx, username, email, googleID, pictureURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *user.User); ok {
		r0 = returnFunc(ctx, username, email, googleID, pictureURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, username, email, googleID, pictureURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_CreateByGoogle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateByGoogle'
type MockUserService_CreateByGoogle_Call struct {
	*mock.Call
}

// CreateByGoogle is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - email string
//   - googleID string
//   - pictureURL string
func (_e *MockUserService_Expecter) CreateByGoogle(ctx any, username any, email any, googleID any, pictureURL any) *MockUserService_CreateByGoogle_Call {
	return &MockUserService_CreateByGoogle_Call{Call: _e.mock.On("CreateByGoogle", ctx, username, email, googleID, pictureURL)}
}

func (_c *MockUserService_CreateByGoogle_Call) Run(run func(ctx context.Context, username string, email string, googleID string, pictureURL string)) *MockUserService_CreateByGoogle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockUserService_CreateByGoogle_Call) Return(user1 *user.User, err error) *MockUserService_CreateByGoogle_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserService_CreateByGoogle_Call) RunAndReturn(run func(ctx context.Context, username string, email string, googleID string, pictureURL string) (*user.User, error)) *MockUserService_CreateByGoogle_Call {
	_c.Call.Return(run)
	return _c
}

// CreateByRegistration provides a mock function for the type MockUserService
func (_mock *MockUserService) CreateByRegistration(ctx context.Context, username string, hashedPassword string) (*user.User, error) {
	ret := _mock.Called(ctx, username, hashedPassword)

	if len(ret) == 0 {
		panic("no return value specified for CreateByRegistration")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*user.User, error)); ok {
		return returnFunc(ctx, username, hashedPassword)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *user.User); ok {
		r0 = returnFunc(ctx, username, hashedPassword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, hashedPassword)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_CreateByRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateByRegistration'
type MockUserService_CreateByRegistration_Call struct {
	*mock.Call
}

// CreateByRegistration is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - hashedPassword string
func (_e *MockUserService_Expecter) CreateByRegistration(ctx any, username any, hashedPassword any) *MockUserService_CreateByRegistration_Call {
	return &MockUserService_CreateByRegistration_Call{Call: _e.mock.On("CreateByRegistration", ctx, username, hashedPassword)}
}

func (_c *MockUserService_CreateByRegistration_Call) Run(run func(ctx context.Context, username string, hashedPassword string)) *MockUserService_CreateByRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_CreateByRegistration_Call) Return(user1 *user.User, err error) *MockUserService_CreateByRegistration_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserService_CreateByRegistration_Call) RunAndReturn(run func(ctx context.Context, username string, hashedPassword string) (*user.User, error)) *MockUserService_CreateByRegistration_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUserService
func (_mock *MockUserService) Delete(ctx context.Context, userID uint, targetID uint) error {
	ret := _mock.Called(ctx, userID, targetID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = returnFunc(ctx, userID, targetID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - targetID uint
func (_e *MockUserService_Expecter) Delete(ctx any, userID any, targetID any) *MockUserService_Delete_Call {
	return &MockUserService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, targetID)}
}

func (_c *MockUserService_Delete_Call) Run(run func(ctx context.Context, userID uint, targetID uint)) *MockUserService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_Delete_Call) Return(err error) *MockUserService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_Delete_Call) RunAndReturn(run func(ctx context.Context, userID uint, targetID uint) error) *MockUserService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByEmail provides a mock function for the type MockUserService
func (_mock *MockUserService) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByEmail")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_ExistsByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByEmail'
type MockUserService_ExistsByEmail_Call struct {
	*mock.Call
}

// ExistsByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserService_Expecter) ExistsByEmail(ctx any, email any) *MockUserService_ExistsByEmail_Call {
	return &MockUserService_ExistsByEmail_Call{Call: _e.mock.On("ExistsByEmail", ctx, email)}
}

func (_c *MockUserService_ExistsByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserService_ExistsByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_ExistsByEmail_Call) Return(b bool, err error) *MockUserService_ExistsByEmail_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserService_ExistsByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (bool, error)) *MockUserService_ExistsByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByUsername provides a mock function for the type MockUserService
func (_mock *MockUserService) ExistsByUsername(ctx context.Context, username string) (bool, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByUsername")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_ExistsByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByUsername'
type MockUserService_ExistsByUsername_Call struct {
	*mock.Call
}

// ExistsByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserService_Expecter) ExistsByUsername(ctx any, username any) *MockUserService_ExistsByUsername_Call {
	return &MockUserService_ExistsByUsername_Call{Call: _e.mock.On("ExistsByUsername", ctx, username)}
}

func (_c *MockUserService_ExistsByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserService_ExistsByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_ExistsByUsername_Call) Return(b bool, err error) *MockUserService_ExistsByUsername_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserService_ExistsByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (bool, error)) *MockUserService_ExistsByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockUserService
func (_mock *MockUserService) Get(ctx context.Context, userID uint) (*user.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*user.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *user.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUserService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockUserService_Expecter) Get(ctx any, userID any) *MockUserService_Get_Call {
	return &MockUserService_Get_Call{Call: _e.mock.On("Get", ctx, userID)}
}

func (_c *MockUserService_Get_Call) Run(run func(ctx context.Context, userID uint)) *MockUserService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_Get_Call) Return(user1 *user.User, err error) *MockUserService_Get_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserService_Get_Call) RunAndReturn(run func(ctx context.Context, userID uint) (*user.User, error)) *MockUserService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type MockUserService
func (_mock *MockUserService) GetByEmail(ctx context.Context, email string) (*user.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockUserService_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserService_Expecter) GetByEmail(ctx any, email any) *MockUserService_GetByEmail_Call {
	return &MockUserService_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockUserService_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserService_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetByEmail_Call) Return(user1 *user.User, err error) *MockUserService_GetByEmail_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserService_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*user.User, error)) *MockUserService_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByProviderID provides a mock function for the type MockUserService
func (_mock *MockUserService) GetByProviderID(ctx context.Context, providerID string) (*user.User, error) {
	ret := _mock.Called(ctx, providerID)

	if len(ret) == 0 {
		panic("no return value specified for GetByProviderID")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return returnFunc(ctx, providerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = returnFunc(ctx, providerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, providerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetByProviderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByProviderID'
type MockUserService_GetByProviderID_Call struct {
	*mock.Call
}

// GetByProviderID is a helper method to define mock.On call
//   - ctx context.Context
//   - providerID string
func (_e *MockUserService_Expecter) GetByProviderID(ctx any, providerID any) *MockUserService_GetByProviderID_Call {
	return &MockUserService_GetByProviderID_Call{Call: _e.mock.On("GetByProviderID", ctx, providerID)}
}

func (_c *MockUserService_GetByProviderID_Call) Run(run func(ctx context.Context, providerID string)) *MockUserService_GetByProviderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetByProviderID_Call) Return(user1 *user.User, err error) *MockUserService_GetByProviderID_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserService_GetByProviderID_Call) RunAndReturn(run func(ctx context.Context, providerID string) (*user.User, error)) *MockUserService_GetByProviderID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsername provides a mock function for the type MockUserService
func (_mock *MockUserService) GetByUsername(ctx context.Context, username string) (*user.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type MockUserService_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserService_Expecter) GetByUsername(ctx any, username any) *MockUserService_GetByUsername_Call {
	return &MockUserService_GetByUsername_Call{Call: _e.mock.On("GetByUsername", ctx, username)}
}

func (_c *MockUserService_GetByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserService_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetByUsername_Call) Return(user1 *user.User, err error) *MockUserService_GetByUsername_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserService_GetByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*user.User, error)) *MockUserService_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// SetPrivilege provides a mock function for the type MockUserService
func (_mock *MockUserService) SetPrivilege(ctx context.Context, userID uint, privilege user.Privilege) error {
	ret := _mock.Called(ctx, userID, privilege)

	if len(ret) == 0 {
		panic("no return value specified for SetPrivilege")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, user.Privilege) error); ok {
		r0 = returnFunc(ctx, userID, privilege)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_SetPrivilege_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPrivilege'
type MockUserService_SetPrivilege_Call struct {
	*mock.Call
}

// SetPrivilege is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - privilege user.Privilege
func (_e *MockUserService_Expecter) SetPrivilege(ctx any, userID any, privilege any) *MockUserService_SetPrivilege_Call {
	return &MockUserService_SetPrivilege_Call{Call: _e.mock.On("SetPrivilege", ctx, userID, privilege)}
}

func (_c *MockUserService_SetPrivilege_Call) Run(run func(ctx context.Context, userID uint, privilege user.Privilege)) *MockUserService_SetPrivilege_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 user.Privilege
		if args[2] != nil {
			arg2 = args[2].(user.Privilege)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_SetPrivilege_Call) Return(err error) *MockUserService_SetPrivilege_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_SetPrivilege_Call) RunAndReturn(run func(ctx context.Context, userID uint, privilege user.Privilege) error) *MockUserService_SetPrivilege_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserService
func (_mock *MockUserService) Update(ctx context.Context, userID uint, targetID uint, req *user.UserPatchRequest) (*user.User, error) {
	ret := _mock.Called(ctx, userID, targetID, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, *user.UserPatchRequest) (*user.User, error)); ok {
		return returnFunc(ctx, userID, targetID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, *user.UserPatchRequest) *user.User); ok {
		r0 = returnFunc(ctx, userID, targetID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint, *user.UserPatchRequest) error); ok {
		r1 = returnFunc(ctx, userID, targetID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - targetID uint
//   - req *user.UserPatchRequest
func (_e *MockUserService_Expecter) Update(ctx any, userID any, targetID any, req any) *MockUserService_Update_Call {
	return &MockUserService_Update_Call{Call: _e.mock.On("Update", ctx, userID, targetID, req)}
}

func (_c *MockUserService_Update_Call) Run(run func(ctx context.Context, userID uint, targetID uint, req *user.UserPatchRequest)) *MockUserService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 *user.UserPatchRequest
		if args[3] != nil {
			arg3 = args[3].(*user.UserPatchRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserService_Update_Call) Return(user1 *user.User, err error) *MockUserService_Update_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserService_Update_Call) RunAndReturn(run func(ctx context.Context, userID uint, targetID uint, req *user.UserPatchRequest) (*user.User, error)) *MockUserService_Update_Call {
	_c.Call.Return(run)
	return _c
}
