// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package embeddings

import (
	"context"
	"io"
	"server/internal/embedding"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEmbeddingsClient creates a new instance of MockEmbeddingsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbeddingsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbeddingsClient {
	mock := &MockEmbeddingsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmbeddingsClient is an autogenerated mock type for the EmbeddingsClient type
type MockEmbeddingsClient struct {
	mock.Mock
}

type MockEmbeddingsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmbeddingsClient) EXPECT() *MockEmbeddingsClient_Expecter {
	return &MockEmbeddingsClient_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockEmbeddingsClient
func (_mock *MockEmbeddingsClient) Delete(ctx context.Context, imageID int) error {
	ret := _mock.Called(ctx, imageID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, imageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmbeddingsClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockEmbeddingsClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID int
func (_e *MockEmbeddingsClient_Expecter) Delete(ctx any, imageID any) *MockEmbeddingsClient_Delete_Call {
	return &MockEmbeddingsClient_Delete_Call{Call: _e.mock.On("Delete", ctx, imageID)}
}

func (_c *MockEmbeddingsClient_Delete_Call) Run(run func(ctx context.Context, imageID int)) *MockEmbeddingsClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmbeddingsClient_Delete_Call) Return(err error) *MockEmbeddingsClient_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmbeddingsClient_Delete_Call) RunAndReturn(run func(ctx context.Context, imageID int) error) *MockEmbeddingsClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Embed provides a mock function for the type MockEmbeddingsClient
func (_mock *MockEmbeddingsClient) Embed(ctx context.Context, file io.Reader) (*embeddings.EmbedResponse, error) {
	ret := _mock.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for Embed")
	}

	var r0 *embeddings.EmbedResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader) (*embeddings.EmbedResponse, error)); ok {
		return returnFunc(ctx, file)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader) *embeddings.EmbedResponse); ok {
		r0 = returnFunc(ctx, file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*embeddings.EmbedResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.Reader) error); ok {
		r1 = returnFunc(ctx, file)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmbeddingsClient_Embed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Embed'
type MockEmbeddingsClient_Embed_Call struct {
	*mock.Call
}

// Embed is a helper method to define mock.On call
//   - ctx context.Context
//   - file io.Reader
func (_e *MockEmbeddingsClient_Expecter) Embed(ctx any, file any) *MockEmbeddingsClient_Embed_Call {
	return &MockEmbeddingsClient_Embed_Call{Call: _e.mock.On("Embed", ctx, file)}
}

func (_c *MockEmbeddingsClient_Embed_Call) Run(run func(ctx context.Context, file io.Reader)) *MockEmbeddingsClient_Embed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmbeddingsClient_Embed_Call) Return(embedResponse *embeddings.EmbedResponse, err error) *MockEmbeddingsClient_Embed_Call {
	_c.Call.Return(embedResponse, err)
	return _c
}

func (_c *MockEmbeddingsClient_Embed_Call) RunAndReturn(run func(ctx context.Context, file io.Reader) (*embeddings.EmbedResponse, error)) *MockEmbeddingsClient_Embed_Call {
	_c.Call.Return(run)
	return _c
}

// EmbedBatch provides a mock function for the type MockEmbeddingsClient
func (_mock *MockEmbeddingsClient) EmbedBatch(ctx context.Context, files []io.Reader) ([]embeddings.EmbedResponse, error) {
	ret := _mock.Called(ctx, files)

	if len(ret) == 0 {
		panic("no return value specified for EmbedBatch")
	}

	var r0 []embeddings.EmbedResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []io.Reader) ([]embeddings.EmbedResponse, error)); ok {
		return returnFunc(ctx, files)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []io.Reader) []embeddings.EmbedResponse); ok {
		r0 = returnFunc(ctx, files)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]embeddings.EmbedResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []io.Reader) error); ok {
		r1 = returnFunc(ctx, files)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmbeddingsClient_EmbedBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmbedBatch'
type MockEmbeddingsClient_EmbedBatch_Call struct {
	*mock.Call
}

// EmbedBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - files []io.Reader
func (_e *MockEmbeddingsClient_Expecter) EmbedBatch(ctx any, files any) *MockEmbeddingsClient_EmbedBatch_Call {
	return &MockEmbeddingsClient_EmbedBatch_Call{Call: _e.mock.On("EmbedBatch", ctx, files)}
}

func (_c *MockEmbeddingsClient_EmbedBatch_Call) Run(run func(ctx context.Context, files []io.Reader)) *MockEmbeddingsClient_EmbedBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []io.Reader
		if args[1] != nil {
			arg1 = args[1].([]io.Reader)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmbeddingsClient_EmbedBatch_Call) Return(embedResponses []embeddings.EmbedResponse, err error) *MockEmbeddingsClient_EmbedBatch_Call {
	_c.Call.Return(embedResponses, err)
	return _c
}

func (_c *MockEmbeddingsClient_EmbedBatch_Call) RunAndReturn(run func(ctx context.Context, files []io.Reader) ([]embeddings.EmbedResponse, error)) *MockEmbeddingsClient_EmbedBatch_Call {
	_c.Call.Return(run)
	return _c
}

// EmbedText provides a mock function for the type MockEmbeddingsClient
func (_mock *MockEmbeddingsClient) EmbedText(ctx context.Context, text string) (*embeddings.EmbedResponse, error) {
	ret := _mock.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for EmbedText")
	}

	var r0 *embeddings.EmbedResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*embeddings.EmbedResponse, error)); ok {
		return returnFunc(ctx, text)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *embeddings.EmbedResponse); ok {
		r0 = returnFunc(ctx, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*embeddings.EmbedResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmbeddingsClient_EmbedText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmbedText'
type MockEmbeddingsClient_EmbedText_Call struct {
	*mock.Call
}

// EmbedText is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockEmbeddingsClient_Expecter) EmbedText(ctx any, text any) *MockEmbeddingsClient_EmbedText_Call {
	return &MockEmbeddingsClient_EmbedText_Call{Call: _e.mock.On("EmbedText", ctx, text)}
}

func (_c *MockEmbeddingsClient_EmbedText_Call) Run(run func(ctx context.Context, text string)) *MockEmbeddingsClient_EmbedText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmbeddingsClient_EmbedText_Call) Return(embedResponse *embeddings.EmbedResponse, err error) *MockEmbeddingsClient_EmbedText_Call {
	_c.Call.Return(embedResponse, err)
	return _c
}

func (_c *MockEmbeddingsClient_EmbedText_Call) RunAndReturn(run func(ctx context.Context, text string) (*embeddings.EmbedResponse, error)) *MockEmbeddingsClient_EmbedText_Call {
	_c.Call.Return(run)
	return _c
}

// SearchImage provides a mock function for the type MockEmbeddingsClient
func (_mock *MockEmbeddingsClient) SearchImage(ctx context.Context, file io.Reader, limit int) ([]embeddings.SearchResult, error) {
	ret := _mock.Called(ctx, file, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchImage")
	}

	var r0 []embeddings.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, int) ([]embeddings.SearchResult, error)); ok {
		return returnFunc(ctx, file, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, int) []embeddings.SearchResult); ok {
		r0 = returnFunc(ctx, file, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]embeddings.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.Reader, int) error); ok {
		r1 = returnFunc(ctx, file, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmbeddingsClient_SearchImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchImage'
type MockEmbeddingsClient_SearchImage_Call struct {
	*mock.Call
}

// SearchImage is a helper method to define mock.On call
//   - ctx context.Context
//   - file io.Reader
//   - limit int
func (_e *MockEmbeddingsClient_Expecter) SearchImage(ctx any, file any, limit any) *MockEmbeddingsClient_SearchImage_Call {
	return &MockEmbeddingsClient_SearchImage_Call{Call: _e.mock.On("SearchImage", ctx, file, limit)}
}

func (_c *MockEmbeddingsClient_SearchImage_Call) Run(run func(ctx context.Context, file io.Reader, limit int)) *MockEmbeddingsClient_SearchImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmbeddingsClient_SearchImage_Call) Return(searchResults []embeddings.SearchResult, err error) *MockEmbeddingsClient_SearchImage_Call {
	_c.Call.Return(searchResults, err)
	return _c
}

func (_c *MockEmbeddingsClient_SearchImage_Call) RunAndReturn(run func(ctx context.Context, file io.Reader, limit int) ([]embeddings.SearchResult, error)) *MockEmbeddingsClient_SearchImage_Call {
	_c.Call.Return(run)
	return _c
}

// SearchVector provides a mock function for the type MockEmbeddingsClient
func (_mock *MockEmbeddingsClient) SearchVector(ctx context.Context, embedding []float32, limit int) ([]embeddings.SearchResult, error) {
	ret := _mock.Called(ctx, embedding, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchVector")
	}

	var r0 []embeddings.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []float32, int) ([]embeddings.SearchResult, error)); ok {
		return returnFunc(ctx, embedding, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []float32, int) []embeddings.SearchResult); ok {
		r0 = returnFunc(ctx, embedding, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]embeddings.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []float32, int) error); ok {
		r1 = returnFunc(ctx, embedding, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmbeddingsClient_SearchVector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchVector'
type MockEmbeddingsClient_SearchVector_Call struct {
	*mock.Call
}

// SearchVector is a helper method to define mock.On call
//   - ctx context.Context
//   - embedding []float32
//   - limit int
func (_e *MockEmbeddingsClient_Expecter) SearchVector(ctx any, embedding any, limit any) *MockEmbeddingsClient_SearchVector_Call {
	return &MockEmbeddingsClient_SearchVector_Call{Call: _e.mock.On("SearchVector", ctx, embedding, limit)}
}

func (_c *MockEmbeddingsClient_SearchVector_Call) Run(run func(ctx context.Context, embedding []float32, limit int)) *MockEmbeddingsClient_SearchVector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []float32
		if args[1] != nil {
			arg1 = args[1].([]float32)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmbeddingsClient_SearchVector_Call) Return(searchResults []embeddings.SearchResult, err error) *MockEmbeddingsClient_SearchVector_Call {
	_c.Call.Return(searchResults, err)
	return _c
}

func (_c *MockEmbeddingsClient_SearchVector_Call) RunAndReturn(run func(ctx context.Context, embedding []float32, limit int) ([]embeddings.SearchResult, error)) *MockEmbeddingsClient_SearchVector_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockEmbeddingsClient
func (_mock *MockEmbeddingsClient) Upsert(ctx context.Context, imageID int, embedding []float32) error {
	ret := _mock.Called(ctx, imageID, embedding)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []float32) error); ok {
		r0 = returnFunc(ctx, imageID, embedding)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmbeddingsClient_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockEmbeddingsClient_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID int
//   - embedding []float32
func (_e *MockEmbeddingsClient_Expecter) Upsert(ctx any, imageID any, embedding any) *MockEmbeddingsClient_Upsert_Call {
	return &MockEmbeddingsClient_Upsert_Call{Call: _e.mock.On("Upsert", ctx, imageID, embedding)}
}

func (_c *MockEmbeddingsClient_Upsert_Call) Run(run func(ctx context.Context, imageID int, embedding []float32)) *MockEmbeddingsClient_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []float32
		if args[2] != nil {
			arg2 = args[2].([]float32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmbeddingsClient_Upsert_Call) Return(err error) *MockEmbeddingsClient_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmbeddingsClient_Upsert_Call) RunAndReturn(run func(ctx context.Context, imageID int, embedding []float32) error) *MockEmbeddingsClient_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockObjectService creates a new instance of MockObjectService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectService {
	mock := &MockObjectService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObjectService is an autogenerated mock type for the ObjectService type
type MockObjectService struct {
	mock.Mock
}

type MockObjectService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectService) EXPECT() *MockObjectService_Expecter {
	return &MockObjectService_Expecter{mock: &_m.Mock}
}

// GetRawImageData provides a mock function for the type MockObjectService
func (_mock *MockObjectService) GetRawImageData(ctx context.Context, id uint) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRawImageData")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) io.ReadCloser); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectService_GetRawImageData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRawImageData'
type MockObjectService_GetRawImageData_Call struct {
	*mock.Call
}

// GetRawImageData is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockObjectService_Expecter) GetRawImageData(ctx any, id any) *MockObjectService_GetRawImageData_Call {
	return &MockObjectService_GetRawImageData_Call{Call: _e.mock.On("GetRawImageData", ctx, id)}
}

func (_c *MockObjectService_GetRawImageData_Call) Run(run func(ctx context.Context, id uint)) *MockObjectService_GetRawImageData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectService_GetRawImageData_Call) Return(readCloser io.ReadCloser, err error) *MockObjectService_GetRawImageData_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockObjectService_GetRawImageData_Call) RunAndReturn(run func(ctx context.Context, id uint) (io.ReadCloser, error)) *MockObjectService_GetRawImageData_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmbeddingsService creates a new instance of MockEmbeddingsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbeddingsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbeddingsService {
	mock := &MockEmbeddingsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmbeddingsService is an autogenerated mock type for the EmbeddingsService type
type MockEmbeddingsService struct {
	mock.Mock
}

type MockEmbeddingsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmbeddingsService) EXPECT() *MockEmbeddingsService_Expecter {
	return &MockEmbeddingsService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockEmbeddingsService
func (_mock *MockEmbeddingsService) Delete(ctx context.Context, id uint) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmbeddingsService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockEmbeddingsService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockEmbeddingsService_Expecter) Delete(ctx any, id any) *MockEmbeddingsService_Delete_Call {
	return &MockEmbeddingsService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockEmbeddingsService_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockEmbeddingsService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmbeddingsService_Delete_Call) Return(err error) *MockEmbeddingsService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmbeddingsService_Delete_Call) RunAndReturn(run func(ctx context.Context, id uint) error) *MockEmbeddingsService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockEmbeddingsService
func (_mock *MockEmbeddingsService) Search(ctx context.Context, query string, limit uint) ([]embeddings.SearchResult, error) {
	ret := _mock.Called(ctx, query, limit)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []embeddings.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint) ([]embeddings.SearchResult, error)); ok {
		return returnFunc(ctx, query, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint) []embeddings.SearchResult); ok {
		r0 = returnFunc(ctx, query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]embeddings.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = returnFunc(ctx, query, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmbeddingsService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockEmbeddingsService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - limit uint
func (_e *MockEmbeddingsService_Expecter) Search(ctx any, query any, limit any) *MockEmbeddingsService_Search_Call {
	return &MockEmbeddingsService_Search_Call{Call: _e.mock.On("Search", ctx, query, limit)}
}

func (_c *MockEmbeddingsService_Search_Call) Run(run func(ctx context.Context, query string, limit uint)) *MockEmbeddingsService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmbeddingsService_Search_Call) Return(searchResults []embeddings.SearchResult, err error) *MockEmbeddingsService_Search_Call {
	_c.Call.Return(searchResults, err)
	return _c
}

func (_c *MockEmbeddingsService_Search_Call) RunAndReturn(run func(ctx context.Context, query string, limit uint) ([]embeddings.SearchResult, error)) *MockEmbeddingsService_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SearchByBytes provides a mock function for the type MockEmbeddingsService
func (_mock *MockEmbeddingsService) SearchByBytes(ctx context.Context, data []byte, limit uint) ([]embeddings.SearchResult, error) {
	ret := _mock.Called(ctx, data, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchByBytes")
	}

	var r0 []embeddings.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, uint) ([]embeddings.SearchResult, error)); ok {
		return returnFunc(ctx, data, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, uint) []embeddings.SearchResult); ok {
		r0 = returnFunc(ctx, data, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]embeddings.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, uint) error); ok {
		r1 = returnFunc(ctx, data, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmbeddingsService_SearchByBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByBytes'
type MockEmbeddingsService_SearchByBytes_Call struct {
	*mock.Call
}

// SearchByBytes is a helper method to define mock.On call
//   - ctx context.Context
//   - data []byte
//   - limit uint
func (_e *MockEmbeddingsService_Expecter) SearchByBytes(ctx any, data any, limit any) *MockEmbeddingsService_SearchByBytes_Call {
	return &MockEmbeddingsService_SearchByBytes_Call{Call: _e.mock.On("SearchByBytes", ctx, data, limit)}
}

func (_c *MockEmbeddingsService_SearchByBytes_Call) Run(run func(ctx context.Context, data []byte, limit uint)) *MockEmbeddingsService_SearchByBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmbeddingsService_SearchByBytes_Call) Return(searchResults []embeddings.SearchResult, err error) *MockEmbeddingsService_SearchByBytes_Call {
	_c.Call.Return(searchResults, err)
	return _c
}

func (_c *MockEmbeddingsService_SearchByBytes_Call) RunAndReturn(run func(ctx context.Context, data []byte, limit uint) ([]embeddings.SearchResult, error)) *MockEmbeddingsService_SearchByBytes_Call {
	_c.Call.Return(run)
	return _c
}

// SearchByImage provides a mock function for the type MockEmbeddingsService
func (_mock *MockEmbeddingsService) SearchByImage(ctx context.Context, id uint, limit uint) ([]embeddings.SearchResult, error) {
	ret := _mock.Called(ctx, id, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchByImage")
	}

	var r0 []embeddings.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) ([]embeddings.SearchResult, error)); ok {
		return returnFunc(ctx, id, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) []embeddings.SearchResult); ok {
		r0 = returnFunc(ctx, id, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]embeddings.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = returnFunc(ctx, id, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmbeddingsService_SearchByImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByImage'
type MockEmbeddingsService_SearchByImage_Call struct {
	*mock.Call
}

// SearchByImage is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - limit uint
func (_e *MockEmbeddingsService_Expecter) SearchByImage(ctx any, id any, limit any) *MockEmbeddingsService_SearchByImage_Call {
	return &MockEmbeddingsService_SearchByImage_Call{Call: _e.mock.On("SearchByImage", ctx, id, limit)}
}

func (_c *MockEmbeddingsService_SearchByImage_Call) Run(run func(ctx context.Context, id uint, limit uint)) *MockEmbeddingsService_SearchByImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmbeddingsService_SearchByImage_Call) Return(searchResults []embeddings.SearchResult, err error) *MockEmbeddingsService_SearchByImage_Call {
	_c.Call.Return(searchResults, err)
	return _c
}

func (_c *MockEmbeddingsService_SearchByImage_Call) RunAndReturn(run func(ctx context.Context, id uint, limit uint) ([]embeddings.SearchResult, error)) *MockEmbeddingsService_SearchByImage_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockEmbeddingsService
func (_mock *MockEmbeddingsService) Upsert(ctx context.Context, id uint, data []byte) error {
	ret := _mock.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, []byte) error); ok {
		r0 = returnFunc(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmbeddingsService_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockEmbeddingsService_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - data []byte
func (_e *MockEmbeddingsService_Expecter) Upsert(ctx any, id any, data any) *MockEmbeddingsService_Upsert_Call {
	return &MockEmbeddingsService_Upsert_Call{Call: _e.mock.On("Upsert", ctx, id, data)}
}

func (_c *MockEmbeddingsService_Upsert_Call) Run(run func(ctx context.Context, id uint, data []byte)) *MockEmbeddingsService_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmbeddingsService_Upsert_Call) Return(err error) *MockEmbeddingsService_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmbeddingsService_Upsert_Call) RunAndReturn(run func(ctx context.Context, id uint, data []byte) error) *MockEmbeddingsService_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertBatch provides a mock function for the type MockEmbeddingsService
func (_mock *MockEmbeddingsService) UpsertBatch(ctx context.Context, id uint, data [][]byte) []error {
	ret := _mock.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpsertBatch")
	}

	var r0 []error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, [][]byte) []error); ok {
		r0 = returnFunc(ctx, id, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}
	return r0
}

// MockEmbeddingsService_UpsertBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertBatch'
type MockEmbeddingsService_UpsertBatch_Call struct {
	*mock.Call
}

// UpsertBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - data [][]byte
func (_e *MockEmbeddingsService_Expecter) UpsertBatch(ctx any, id any, data any) *MockEmbeddingsService_UpsertBatch_Call {
	return &MockEmbeddingsService_UpsertBatch_Call{Call: _e.mock.On("UpsertBatch", ctx, id, data)}
}

func (_c *MockEmbeddingsService_UpsertBatch_Call) Run(run func(ctx context.Context, id uint, data [][]byte)) *MockEmbeddingsService_UpsertBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 [][]byte
		if args[2] != nil {
			arg2 = args[2].([][]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmbeddingsService_UpsertBatch_Call) Return(errs []error) *MockEmbeddingsService_UpsertBatch_Call {
	_c.Call.Return(errs)
	return _c
}

func (_c *MockEmbeddingsService_UpsertBatch_Call) RunAndReturn(run func(ctx context.Context, id uint, data [][]byte) []error) *MockEmbeddingsService_UpsertBatch_Call {
	_c.Call.Return(run)
	return _c
}
